// Every string a person can read in the app lives here (readings and their anchor phrases
// live in readings.json, moves in catalogue.json), so one test can check all of them against
// the plan's rule: a reading, never a verdict.
export const copy = {
  appName: 'Life Mirror',
  tabs: {
    now: 'Now',
    mirror: 'Mirror',
    moves: 'Moves',
    aims: 'Aims',
    settings: 'Settings',
  },
  blocks: {
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
  },
  stances: {
    Protect: 'Protect',
    Recover: 'Recover',
    Stabilize: 'Stabilize',
    Build: 'Build',
  },
  now: {
    notLogged: 'Not logged yet',
    checkIn: 'Check in',
    continue: 'Continue',
    logged: 'Logged {time}',
    incomplete: '{n} of {total} answered',
    from: 'From {time}',
    earlier: 'Earlier',
  },
  today: {
    now: 'Open now',
    logged: 'Logged',
    checkIn: 'Check in · {block}',
    continue: 'Continue · {block}',
    context: 'Today, if different',
    awayToday: "She's away today",
    studyNight: 'Study night',
    notStudyNight: 'Not a study night today',
    note: 'Statements, not commands. Only exceptions to the week live here; they change today alone.',
  },
  study: {
    fact: 'Study night',
    kept: '{kept} kept of {total}',
    eyebrow: 'Study night',
    sized: '{n} min · sized to one sitting',
    start: 'Start it',
    notNow: 'Not now',
    whyQuestion: 'One optional tap: why not?',
    reasons: { tired: 'Tired', tooMuch: 'Too much on', noTime: 'No time', didntWant: "Didn't want to" },
    leave: 'Leave it',
    said: 'You said {reason}. Tonight {evidence}.',
    evidence: '{reading} reads {phrase}',
    smaller: '{name} instead?',
    patternWeekday: "You've said {reason} the last {n} {weekday}.",
    patternAll: "You've said {reason} the last {n} study nights.",
    continue: 'Continue',
    note: 'You decide. The app never overrides you; it only never lets the skip be silent.',
  },
  reading: {
    recipe: '{used} of {total} ingredients · equal weights',
    at: '{block} {time}',
    atDay: '{day}, {block} {time}',
    incomplete: 'Incomplete',
    soFar: '{n} of {total} ingredients answered so far · no number until all six are in',
    none: 'Not logged yet',
    noneNote: 'The reading out of 100 appears after a completed check-in.',
    scaleEmpty: 'The scale from 0 to 100, no reading yet',
    context: 'Context',
    today: 'Today so far',
  },
  direction: {
    title: 'Your direction',
    ask: 'One line about where you are going. Yours, kept on this phone only, shown back to you later. Asked once; change it any time in Settings.',
    placeholder: 'One line',
    save: 'Keep it',
    notNow: 'Not now',
    note: 'Nothing here leaves the phone.',
    settingsNote: 'Shown back to you at the moments that matter. Never counted, never graded.',
    edit: 'Your direction',
  },
  week: {
    title: 'The week',
    note: 'The shape of your week, known from day one, no learning needed. It stays on this phone.',
    churchDay: 'Church day',
    none: 'None',
    livesWithMe: 'She lives with me',
    livesWithMeNote: "The constant. The exception is one chip in the evening check-in: She's away today.",
    studyNights: 'Study nights',
    pickup: 'Daycare pickup',
    pickupOn: 'There is a pickup',
    pickupTime: 'Pickup time',
    soloUntil: 'Solo hours run until',
    days: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
  },
  win: {
    today: 'Minimum win today',
  },
  checkin: {
    progress: '{block} · {n} of {total}',
    back: 'Back',
    close: 'Close',
    clear: 'Clear this answer',
  },
  summary: {
    logged: '{block} · logged {time}',
    incomplete: '{block} · incomplete',
    readings: 'Readings',
    extras: 'Extras',
    changeExtras: 'Change the extras',
    notLogged: 'Not logged yet',
    finishFirst: 'Finish the readings and this card says what changed.',
    done: 'Done',
    delete: 'Delete this check-in',
    deleteConfirm: 'Tap again to delete it',
  },
  since: {
    heading: 'Since {when}',
    first: 'Your first reading. From the next one, this card says what changed.',
    sameDay: 'this {block}',
    yesterday: 'yesterday {block}',
    weekday: '{weekday} {block}',
    date: '{date}, {block}',
    up: '{name} up {amount}',
    down: '{name} down {amount}',
    unchanged: 'Unchanged: {list}',
    nothingShared: 'Nothing to compare with the last check-in.',
  },
  amounts: {
    step: ['one step', 'two steps', 'three steps', 'four steps'],
    band: ['one band', 'two bands', 'three bands', 'four bands'],
  },
  extras: {
    title: 'Evening extras',
    note: 'All optional. One tap each.',
    yesterdayWin: "Yesterday's minimum win",
    winOutcome: { done: 'Done', partly: 'Partly', no: 'No' },
    tomorrowWin: "Tomorrow's minimum win",
    winPlaceholder: 'One line, sized to one sitting',
    winSet: 'Set for tomorrow.',
    caffeine: 'Caffeine after midday',
    dinner: 'Late or heavy dinner',
    faith: 'Felt close to God today?',
    faithOff: 'Turn this question off',
    private: 'Private log',
    privateLogged: '{n} logged',
    yes: 'Yes',
    logged: 'Logged',
    done: 'Done',
    chips: 'How today landed',
    nothingLanded: 'Nothing landed today',
    hardToSeePoint: 'Hard to see the point today',
    chipFirst: 'First time recorded.',
    chipTimes: '{n} times before. The day after, your readings averaged {mean} across {k} check-ins.',
    chipTimesNoNext: '{n} times before. No readings from the day after yet.',
    chipDirection: 'Your direction: {line}',
    noteLabel: 'Anything the app has no question for',
    notePlaceholder: 'One line, kept for the export',
  },
  mirror: {
    today: 'Today',
    week: 'The week',
    heatmap: 'Days by blocks',
    together: 'Moves together',
    overlay: 'Overlay a context reading',
    overlayNone: 'Reading only',
    todayCaption: '{n} of 3 blocks logged · the reading out of 100 by block · an overlay shows a context reading on the same scale',
    weekCaption: 'Seven days · each dot one block · a gap is Not logged yet',
    heatCaption: 'Brighter is higher · an empty outline is Not logged yet · {days} days',
    togetherNote: 'Moving together is not causing.',
    togetherCaption: 'Rank correlation between two readings across the check-ins where both were answered. Pairs with fewer than {min} shared check-ins are not shown.',
    togetherEmpty: 'Nothing to show yet: no pair of readings has {min} shared check-ins.',
    shared: 'n {n}',
    empty: 'Nothing logged yet. The mirror draws from your check-ins.',
  },
  catalogue: {
    title: 'The catalogue',
    count: '{n} moves · {families} families',
    read: 'Read the catalogue',
    readNote: 'Every move, with its source. Read it all, then veto by name.',
    intro: 'Every move the app may offer, with where it comes from and how strong that evidence is, what it takes, what it should move and over what window, what it never sits alongside, and what it counts toward.',
    strengthNote: 'Strength of evidence: strong means meta-analyses or several trials; moderate a good trial or review; thin a small study or evidence for something adjacent; practice common advice, untested.',
    vetoNote: 'Yellow names entries to cut or reword.',
    minutes: '{n} min',
    noTime: 'No time, a decision',
    effort: 'effort to start {level}',
    efforts: { low: 'low', medium: 'medium', high: 'high' },
    needsLabel: 'needs {needs}',
    needsNothing: 'nothing',
    needs: { outdoors: 'outdoors', kit: 'kit', anotherPerson: 'another person', freeHour: 'a free hour', daylight: 'daylight', quiet: 'quiet' },
    shouldMove: 'Should move',
    windows: { nextBlock: 'next block', evening: 'this evening', nextMorning: 'next morning', sevenDays: 'seven days' },
    when: 'When',
    countsToward: 'counts toward',
    counters: { study: 'study', conversations: 'conversations', timeWithHer: 'time with her', faith: 'faith', finishing: 'finishing' },
    notAlongside: 'Not alongside',
    standsInFor: 'Stands in for',
    strengths: { strong: 'Strong evidence', moderate: 'Moderate evidence', weak: 'Thin evidence', practice: 'Practice, untested' },
  },
  move: {
    title: 'One small move',
    pickupTitle: 'Before pickup',
    nothing: 'Nothing today',
    nothingWhat: 'On purpose. Nothing extra this block; the record will show what that does.',
    why: 'Why this',
    evidence: 'Evidence for you',
    testing: 'Testing',
    whyNot: 'Why not that',
    whyLine: '{target} is your lowest reading right now. This should move it {arrow} over the {window}.',
    whyNothing: '{target} is your lowest reading right now. Nothing extra is one of the candidates, so the record can say what doing nothing does.',
    whyPickup: 'Its only job is arriving at pickup with something left.',
    evidenceLine: 'offered {n} in this situation, done {done}, partly {partly}.',
    once: 'once',
    twice: 'twice',
    nTimes: '{n} times',
    tierLittle: 'Little evidence',
    testingLine: '{move} against {alternative}, for {target} over the {window}. Card {id}, written {date}. A worthwhile change is one step.',
    testingNone: 'No alternative to test against in this situation yet.',
    coinFlip: 'This offer was a coin flip, so honest claims survive.',
    whyNotLine: 'Not {move}: {reason}.',
    whyNotReasons: {
      draw: 'the draw favoured this one today',
      coinFlip: 'this offer was a coin flip',
      observed: 'bedtime itself is observed, never offered',
      passive: 'it rides alongside a move rather than being one',
      study: 'study is offered at the evening check-in on study nights',
      schedule: 'it is not on today, by your week',
      block: 'it does not fit this block',
      hidden: 'its family is hidden',
      target: 'it does not move your lowest reading',
      band: 'your reading rules out its effort right now',
      offeredToday: 'it was offered today already',
      conflict: 'it sits badly with something done or offered today',
      rung: 'it is a harder rung than the readings allow',
    },
    alongside: 'Alongside',
    skip: 'Skip · show the next',
    hideFaith: 'Hide faith moves',
    pending: 'Asked at your next check-in.',
    happened: 'What happened',
    passedOver: 'Passed over at the next check-in.',
    none: 'Log a check-in and one small move follows.',
    hidden: 'Moves stay hidden while Low-demand mode is on.',
    knows: 'How much it knows: {weeks} weeks of record. Offers are still drawn evenly from what fits, low starting effort first; research priors arrive with Phase 8 and your record steers them from Phase 9.',
  },
  ask: {
    title: 'Last time, one small move',
    titlePickup: 'Before pickup, last time',
    question: 'Did you do it?',
    questionNothing: 'Did you keep it to nothing extra?',
    skip: 'Not now',
    whyQuestion: 'One optional tap: why not?',
    why: { noTime: 'No time', didntWant: "Didn't want to" },
    whySkip: 'Leave it',
    passiveQuestion: 'And {item}?',
    passiveDone: 'Happened',
    passiveNo: "Didn't",
    note: 'One tap. What happened is recorded apart from what was offered.',
  },
  history: {
    title: 'History',
    count: '{n} offers',
    empty: 'No moves offered yet. Complete a check-in and one follows.',
    offer: 'Offer {id}',
    card: 'Card {id} · {window}',
    noCard: 'No card',
    outcome: 'Outcome {id}',
    noOutcome: 'No outcome yet',
    pending: 'Pending',
    unanswered: 'Not answered',
    skipped: 'Skipped',
    coinFlip: 'coin flip',
    pickup: 'before pickup',
    study: 'study night',
  },
  movesTab: {
    historyNote: 'Every offer, its card, and what happened, as three separate records.',
    tiersNote: 'Evidence tiers beyond counts arrive with Phase 9. Until then every move says Little evidence, with its counts.',
  },
  panels: {
    aims: {
      title: 'Your protected next step',
      body: "Commitments you choose, each with a next step pre-filled from the ladder or the catalogue, held above the move so tonight's reading cannot push it aside. The proof ladder for the certification, follow-through as counts, and your direction sentence shown back.",
      when: 'Arrives with Phase 7.',
    },
    strip: 'Phases 0 to {shipped} of {last} shipped · this one arrives with Phase {phase}',
  },
  data: {
    title: 'Data',
    export: 'Export',
    exportNote: 'Everything you recorded, as JSON and CSV, handed to the share sheet. The app sends nothing anywhere.',
    includePrivate: 'Include private items by name',
    exportButton: 'Export JSON and CSV',
    exporting: 'Preparing…',
    lastExport: 'Last export {when}.',
    neverExported: 'Not exported yet.',
    exportFailed: 'The share sheet did not open. Try again from the installed app.',
    deleteTitle: 'Delete everything',
    deleteNote: 'Every check-in, win, private item and setting on this phone. Nothing is kept anywhere else, so nothing comes back.',
    deleteStart: 'Delete everything',
    deleteWord: 'delete',
    deletePrompt: 'Type {word} to confirm.',
    deleteConfirm: 'Delete it all',
    deleteCancel: 'Keep it',
  },
  settings: {
    checkins: 'Check-ins',
    depth: 'Depth',
    depthFull: 'Full',
    depthShort: 'Short',
    depthNote: 'Short asks mood, energy and stress in every block.',
    frequency: 'Frequency',
    freqThree: 'Three a day',
    freqTwo: 'Morning and evening',
    freqOne: 'Evening only',
    lowDemand: 'Low-demand mode',
    lowDemandNote: 'For rough weeks: short depth, evening only, one reminder, no move, no coin flips. Off restores what you had.',
    quiet: 'Quiet hours',
    quietFrom: 'From',
    quietTo: 'To',
    quietNote: 'No reminders in quiet hours.',
    reminders: 'Reminders',
    remindersOn: 'Remind me',
    reminderTime: '{block} reminder',
    remindersNote: 'One reminder per block, worded the same every time. None in quiet hours, none for a block already begun.',
    inAppNote: 'With the app open in the background it reminds you itself at these times. To be rung with the app closed, set up the ping.',
    remindersDenied: "Notifications are off for this app in the phone's settings.",
    remindersUnsupported: 'This browser offers no notifications here.',
    pushTitle: 'The ping',
    pushSetup: 'Set up the ping',
    pushCopy: 'Copy address',
    pushCopied: 'Copied',
    pushShow: 'Show address',
    pushHide: 'Hide address',
    pushUnsubscribe: 'Unsubscribe',
    pushSubscribedAt: 'Set up {when}.',
    pushChanged: 'The address changed. Copy it again and paste it to the builder.',
    pushUnsupported: 'This browser has no push here. Open the installed app on the phone.',
    pushNote:
      'A content-free ping arrives at 07:30, 13:00 and 19:30 (America/New_York), sent from your own repository. The worker on this phone decides whether to show anything. This address is the only thing that ever leaves the phone; it carries no content, and Unsubscribe kills it. Paste it to the builder once.',
    movesSection: 'Moves',
    offerFaith: 'Offer faith moves',
    offerFaithNote: 'Off hides the whole family with one tap. Nothing is counted either way.',
    extras: 'Evening extras',
    extraWin: "Tomorrow's minimum win",
    extraCaffeine: 'Caffeine after midday',
    extraDinner: 'Late or heavy dinner',
    extraPrivate: 'Private log',
    extraFaith: 'Felt close to God today?',
    faithNote: 'Off stays off until you turn it on here. Never counted, never a streak.',
    more: 'More',
    dataRow: 'Data',
    dataRowNote: 'Export everything, or delete everything.',
    private: 'Private',
    privateNote: 'Items you name, measured, shown nowhere else unless you choose.',
    wording: 'Wording',
    wordingNote: 'The 13 readings and their 65 phrases.',
    legend: 'Legend',
    legendNote: 'How facts, calculations and conclusions are told apart.',
    about: 'About',
    app: 'App',
    build: 'Build',
    builtAt: 'Built',
    run: 'Open the run that tested this build',
    runMissing: 'Built outside the pipeline, so there is no run to show.',
    testsOne: '{n} unit test passed before this build.',
    testsMany: '{n} unit tests passed before this build.',
    testsUnknown: 'Test count not recorded for this build.',
    data: 'Data',
    dataNote: 'Your check-ins and settings are stored on this phone only. Nothing leaves it but the ping address, if you set one up, and whatever you choose to export.',
    phase: 'Phase 6 of the build plan: one move.',
  },
  private: {
    title: 'Private',
    note: 'Named here only. Never in an export unless you tick them. Never in any document.',
    none: 'Nothing named yet.',
    placeholder: 'Name it',
    add: 'Add',
    remove: 'Remove',
    show: 'Show private items by name outside this screen',
  },
  legend: {
    title: 'Legend',
    intro: 'Three kinds of thing appear on screen, and they always look different.',
    facts: 'Facts',
    factsNote: 'What you tapped and when. Plain text.',
    calcs: 'Calculations',
    calcsNote: 'Numbers the app derives from facts, always with their recipe. Set off by a thin rule on the left; every chart carries its caption.',
    conclusions: 'Conclusions',
    conclusionsNote: 'What the app claims to have learned. Arrives with Phase 9 and always carries its evidence tier.',
    recipe: 'The reading out of 100',
    recipeNote:
      'Six readings have a clear better direction: mood, energy and focus up; stress, overwhelm and irritation down. Each phrase maps to 0, 25, 50, 75 or 100, reversed where lower is better. The reading is their equal-weight mean; every block asks all six, and a block missing any of them reads Incomplete, never a number. Weights stay equal until a learned weighting clears the bar in Phase 9.',
    stances: 'Stances',
    stancesNote: '0 to 24 Protect · 25 to 49 Recover · 50 to 74 Stabilize · 75 to 100 Build',
    context: 'Context',
    contextNote: 'Hunger, sleep, confidence, loneliness and social energy sit beside the reading. They never enter it.',
    silence: 'Silence',
    silenceNote: 'An unanswered question shows Not logged yet. It changes no number, fills no gap on a chart, and prompts no catch-up.',
  },
  wording: {
    intro: 'Five phrases per reading, least to most. You pick a phrase, never a number.',
    sets: 'Morning asks all 13. Afternoon asks seven: mood, irritation, energy, hunger, stress, focus, overwhelm. Evening asks those and loneliness. Every block feeds all six ingredients of the reading.',
  },
  reminders: {
    body: 'Time for your {block} check-in.',
    quiet: 'Nothing due right now.',
  },
} as const
