// Every string a person can read in the app lives here (readings and their anchor phrases
// live in readings.json, moves in catalogue.json), so one test can check all of them against
// the plan's rule: a reading, never a verdict.
export const copy = {
  appName: 'Life Mirror',
  tabs: {
    now: 'Now',
    mirror: 'Mirror',
    moves: 'Moves',
    aims: 'Aims',
    settings: 'Settings',
  },
  blocks: {
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
  },
  stances: {
    Protect: 'Protect',
    Recover: 'Recover',
    Stabilize: 'Stabilize',
    Build: 'Build',
  },
  bands: {
    empty: 'Empty',
    wornDown: 'Worn down',
    gettingBy: 'Getting by',
    solid: 'Solid',
    firing: 'Firing',
  },
  now: {
    notLogged: 'Not logged yet',
    checkIn: 'Check in',
    continue: 'Continue',
    logged: 'Logged {time}',
    incomplete: '{n} of {total} answered',
    from: 'From {time}',
    earlier: 'Earlier',
  },
  today: {
    now: 'Open now',
    logged: 'Logged',
    checkIn: 'Check in · {block}',
    continue: 'Continue · {block}',
    context: 'Today, if different',
    awayToday: "She's away today",
    studyNight: 'Study night',
    notStudyNight: 'Not a study night today',
    note: 'Statements, not commands. Only exceptions to the week live here; they change today alone.',
  },
  study: {
    fact: 'Study night',
    kept: '{kept} kept of {total}',
    eyebrow: 'Study night',
    sized: '{n} min · sized to one sitting',
    start: 'Start it',
    notNow: 'Not now',
    whyQuestion: 'One optional tap: why not?',
    reasons: { tired: 'Tired', tooMuch: 'Too much on', noTime: 'No time', didntWant: "Didn't want to" },
    leave: 'Leave it',
    said: 'You said {reason}. Tonight {evidence}.',
    evidence: '{reading} reads {phrase}',
    smaller: '{name} instead?',
    smallerMinutes: '{n} minutes of it instead?',
    smallest: 'This is already the smallest version. It stays on offer; you decide.',
    patternWeekday: "You've said {reason} the last {n} {weekday}.",
    patternAll: "You've said {reason} the last {n} study nights.",
    continue: 'Continue',
    note: 'You decide. The app never overrides you; it only never lets the skip be silent.',
  },
  reading: {
    recipe: '{used} of {total} ingredients · {weights}',
    equalWeights: 'equal weights',
    learnedWeights: 'learned weights, from a weight card that held up',
    at: '{block} {time}',
    atDay: '{day}, {block} {time}',
    incomplete: 'Incomplete',
    soFar: '{n} of {total} ingredients answered so far · no number until all six are in',
    none: 'Not logged yet',
    noneNote: 'The reading out of 100 appears after a completed check-in.',
    scaleEmpty: 'The scale from 0 to 100, no reading yet',
    context: 'Context',
    today: 'Today so far',
  },
  direction: {
    title: 'Your direction',
    ask: 'One line about where you are going. Yours, kept with your record, shown back to you later. Asked once; change it any time in Settings.',
    placeholder: 'One line',
    save: 'Keep it',
    notNow: 'Not now',
    note: 'Nothing here goes anywhere but your own record.',
    settingsNote: 'Shown back to you at the moments that matter. Never counted, never graded.',
    edit: 'Your direction',
  },
  week: {
    title: 'The week',
    note: 'The shape of your week, known from day one, no learning needed.',
    churchDay: 'Church day',
    none: 'None',
    livesWithMe: 'She lives with me',
    livesWithMeNote: "The constant. The exception is one chip in the evening check-in: She's away today.",
    studyNights: 'Study nights',
    pickup: 'Daycare pickup',
    pickupOn: 'There is a pickup',
    pickupTime: 'Pickup time',
    soloUntil: 'Solo hours run until',
    days: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
  },
  win: {
    today: 'Minimum win today',
  },
  checkin: {
    progress: '{block} · {n} of {total}',
    back: 'Back',
    close: 'Close',
    clear: 'Clear this answer',
  },
  summary: {
    logged: '{block} · logged {time}',
    incomplete: '{block} · incomplete',
    readings: 'Readings',
    extras: 'Extras',
    changeExtras: 'Change the extras',
    notLogged: 'Not logged yet',
    finishFirst: 'Finish the readings and this card says what changed.',
    done: 'Done',
    delete: 'Delete this check-in',
    deleteConfirm: 'Tap again to delete it',
  },
  since: {
    heading: 'Since {when}',
    first: 'Your first reading. From the next one, this card says what changed.',
    sameDay: 'this {block}',
    yesterday: 'yesterday {block}',
    weekday: '{weekday} {block}',
    date: '{date}, {block}',
    up: '{name} up {amount}',
    down: '{name} down {amount}',
    unchanged: 'Unchanged: {list}',
    nothingShared: 'Nothing to compare with the last check-in.',
  },
  amounts: {
    step: ['one step', 'two steps', 'three steps', 'four steps'],
    band: ['one band', 'two bands', 'three bands', 'four bands'],
  },
  extras: {
    title: 'Evening extras',
    note: 'All optional. One tap each.',
    yesterdayWin: "Yesterday's minimum win",
    winOutcome: { done: 'Done', partly: 'Partly', no: 'No' },
    tomorrowWin: "Tomorrow's minimum win",
    winPlaceholder: 'One line, sized to one sitting',
    winSet: 'Set for tomorrow.',
    caffeine: 'Caffeine after midday',
    dinner: 'Late or heavy dinner',
    faith: 'Felt close to God today?',
    faithOff: 'Turn this question off',
    private: 'Private log',
    privateLogged: '{n} logged',
    yes: 'Yes',
    logged: 'Logged',
    done: 'Done',
    chips: 'How today landed',
    nothingLanded: 'Nothing landed today',
    hardToSeePoint: 'Hard to see the point today',
    chipFirst: 'First time recorded.',
    chipTimes: '{n} times before. The morning after read {mean}, against {without} after evenings that started the same ({k} and {m}).',
    chipTimesNoNext: '{n} times before. No readings from the morning after yet.',
    chipUnmatched: '{n} times before. The morning after read {mean} ({k}); nothing yet to set it against.',
    coolingOff: 'A cooling-off event today',
    bigSocial: 'A big social event today, unplanned',
    coolingAnswer: 'Cooling off ran about {blocks} blocks after the last {events}.',
    recoveryNote: 'The recovery gap rides alongside tomorrow evening’s move.',
    chipDirection: 'Your direction: {line}',
    noteLabel: 'Anything the app has no question for',
    notePlaceholder: 'One line, kept for the export',
  },
  mirror: {
    today: 'Today',
    week: 'The week',
    heatmap: 'Days by blocks',
    together: 'Moves together',
    overlay: 'Overlay a context reading',
    overlayNone: 'Reading only',
    todayCaption: '{n} of 3 blocks logged · the reading out of 100 by block · an overlay shows a context reading on the same scale',
    weekCaption: 'Seven days · each dot one block · a gap is Not logged yet',
    heatCaption: 'Brighter is higher · an empty outline is Not logged yet · {days} days',
    togetherNote: 'Moving together is not causing.',
    togetherCaption: 'Rank correlation between two readings across the check-ins where both were answered. Pairs with fewer than {min} shared check-ins are not shown.',
    togetherEmpty: 'Nothing to show yet: no pair of readings has {min} shared check-ins.',
    shared: 'n {n}',
    empty: 'Nothing logged yet. The mirror draws from your check-ins.',
  },
  catalogue: {
    title: 'The catalogue',
    count: '{n} moves · {proposed} proposed',
    read: 'Read the catalogue',
    readNote: 'Every move, with its source. Read it all, then veto by name.',
    intro: 'Every move the app may offer, with where it comes from and how strong that evidence is, what it takes and what it costs to be given, its tags, its starting belief, what it should move and over what window, what it never sits alongside, and what it counts toward.',
    strengthNote: 'Strength of evidence: strong means meta-analyses or several trials; moderate a good trial or review; thin a small study or evidence for something adjacent; practice common advice, untested.',
    vetoNote: 'Yellow names entries, tags, beliefs or alternates to cut or reword. Green wires the proposals; until then nothing here changes what is offered.',
    minutes: '{n} min',
    noTime: 'No time, a decision',
    effort: 'effort to start {level}',
    efforts: { low: 'low', medium: 'medium', high: 'high' },
    needsLabel: 'needs {needs}',
    needsNothing: 'nothing',
    needs: { outdoors: 'outdoors', kit: 'kit', anotherPerson: 'another person', freeHour: 'a free hour', daylight: 'daylight', quiet: 'quiet' },
    shouldMove: 'Should move',
    windows: { nextBlock: 'next block', laterToday: 'later that day', evening: 'evening', nextMorning: 'next morning', sevenDays: 'seven days' },
    tags: 'Tags',
    tagNames: { outdoors: 'outdoors', withPeople: 'with people', short: 'short', lowEffort: 'low effort', pleasure: 'pleasure', mastery: 'mastery', connection: 'connection', intensity: 'intensity' },
    intensity: 'intensity {level}',
    costLabel: 'cost to assign {level}',
    prior: 'Starting belief',
    priorLine: '{target} {arrow} by about {effect} of a step over the {window}',
    effectWords: { '0': 'no change, until your record says', '0.1': 'a tenth', '0.2': 'a fifth', '0.3': 'a third', '0.4': 'four tenths', '0.5': 'half' },
    proposed: 'Proposed',
    proposedNote: 'read and veto; joins the candidates at Green',
    parkProposed: 'Proposed to park',
    parked: 'Parked · shown here, never offered',
    ladderRung: 'rung {n} of the participation ladder',
    setupKinds: {
      lateness: 'a setup for chronic lateness',
      friction: 'removes a step before a move, for good',
      appointment: 'closes an avoided task, for good',
      default: 'a default that holds without reminders',
      necessity: 'a setup whose target is a necessity: {necessity}',
    },
    necessities: { food: 'food', teeth: 'teeth', shower: 'the shower' },
    passiveProposed: 'proposed as a passive item',
    learnedTitle: 'Learned tags and their starting beliefs',
    learnedNote: 'From Phase 10 the app estimates each tag’s effect from your record, starting from these. No more learned tags than these.',
    filterTitle: 'Filter tags',
    filterNote: 'These only select. They are never learned.',
    researchTitle: 'The research the layer rests on',
    researchNote: 'Read before wiring: what each body of work contributes as entries, as tags, and as the wording of the two evening chips.',
    contributes: 'What it contributes',
    chipsLabel: 'The two chips',
    extensionTitle: 'The extension prompt, as the app will write it',
    tradesTitle: 'Proposed trades',
    wiringLabel: 'What Green wires',
    when: 'When',
    countsToward: 'counts toward',
    counters: { study: 'study', conversations: 'conversations', timeWithHer: 'time with her', faith: 'faith', finishing: 'finishing' },
    notAlongside: 'Not alongside',
    standsInFor: 'Stands in for',
    strengths: { strong: 'Strong evidence', moderate: 'Moderate evidence', weak: 'Thin evidence', practice: 'Practice, untested' },
  },
  move: {
    title: 'One small move',
    pickupTitle: 'Before pickup',
    nothing: 'Nothing today',
    nothingWhat: 'On purpose. Nothing extra this block; the record will show what that does.',
    why: 'Why this',
    evidence: 'Evidence for you',
    testing: 'Testing',
    whyNot: 'Why not that',
    whyLine: '{target} is your lowest reading right now. This should move it {arrow} over the {window}.',
    whyNothing: '{target} is your lowest reading right now. Nothing extra is one of the candidates, so the record can say what doing nothing does.',
    whyPickup: 'Its only job is arriving at pickup with something left.',
    evidenceLine: 'offered {n} in this situation, done {done}, partly {partly}.',
    once: 'once',
    twice: 'twice',
    nTimes: '{n} times',
    tierLittle: 'Little evidence',
    testingLine: '{move} against {alternative}, for {target} over the {window}. Card {id}, written {date}. A worthwhile change is one step.',
    testingNone: 'No alternative to test against in this situation yet.',
    coinFlip: 'This offer was a coin flip, so honest claims survive.',
    whyNotLine: 'Not {move}: {reason}.',
    whyNotReasons: {
      draw: 'the draw favoured this one today',
      coinFlip: 'this offer was a coin flip',
      observed: 'bedtime itself is observed, never offered',
      passive: 'it rides alongside a move rather than being one',
      study: 'study is offered at the evening check-in on study nights',
      schedule: 'it is not on today, by your week',
      block: 'it does not fit this block',
      hidden: 'its family is hidden',
      target: 'it does not move your lowest reading',
      band: 'your reading rules out its effort right now',
      offeredToday: 'it was offered today already',
      conflict: 'it sits badly with something done or offered today',
      rung: 'it is a harder rung than the readings allow',
      proposed: 'it is proposed, not yet wired',
      parked: 'it is parked',
      noTime: 'you said no time for something this long in this block this week',
    },
    alongside: 'Alongside',
    skip: 'Skip · show the next',
    done: 'Done',
    doneLine: '{name} · {state} · {time}',
    hideFaith: 'Hide faith moves',
    pending: 'Asked at your next check-in.',
    happened: 'What happened',
    passedOver: 'Passed over at the next check-in.',
    none: 'Log a check-in and one small move follows.',
    hidden: 'Moves stay hidden while Low-demand mode is on.',
    privateInline: 'Your record: evenings with {name} logged, the morning after read {with} against {without} after evenings that started the same ({n} and {m}). An alternative: {alternative}.',
    knows: 'How much it knows: {weeks} weeks of record. Offers are still drawn evenly from what fits, low starting effort first; each offer now draws from research corrected by your record, recent days weighing more; nothing here is a claim until its card says so.',
  },
  ask: {
    title: 'Last time, one small move',
    titlePickup: 'Before pickup, last time',
    titleStep: 'Your aim, last time',
    titleUnblock: 'Unblocking, last time',
    question: 'Did you do it?',
    questionNothing: 'Did you keep it to nothing extra?',
    skip: 'Not now',
    whyQuestion: 'One optional tap: why not?',
    why: { noTime: 'No time', didntWant: "Didn't want to" },
    whySkip: 'Leave it',
    passiveQuestion: 'And {item}?',
    passiveDone: 'Happened',
    passiveNo: "Didn't",
    note: 'One tap. What happened is recorded apart from what was offered.',
  },
  readingsScreen: {
    title: 'Readings and chips',
    row: 'Readings and chips',
    rowNote: 'Retirement proposals, decided by you; chips that stopped appearing; anchor swaps.',
    proposals: 'Retirement proposals',
    proposalsNote: 'A context reading is proposed for retirement only when both conditions hold on your record: it adds no real distinction, and no predictive value. Never automatic; you decide. An ingredient is never proposed.',
    none: 'No proposal. Every reading is earning its place on the record so far.',
    twin: '{name} moves with {other}: rank correlation {r} over {n} shared check-ins.',
    flat: '{name} sits on the same phrase {share} percent of the time over {n} answers.',
    prediction: 'It foretells the next block’s reading no better than nothing: correlation {r} over {n} pairs.',
    retire: 'Retire it',
    keep: 'Keep it for now',
    retired: 'Retired readings',
    retiredNone: 'None.',
    bringBack: 'Bring it back',
    chips: 'Chips',
    chipsNote: 'A chip you never tap stops appearing after thirty logged evenings. One tap here brings it back.',
    chipOn: 'appearing · last tapped {when}',
    chipNever: 'appearing · never tapped, {n} evenings so far',
    chipRetired: 'stopped after {n} evenings without a tap',
    chipNames: {
      nothingLanded: 'Nothing landed today',
      hardToSeePoint: 'Hard to see the point today',
      coolingOff: 'A cooling-off event today',
      bigSocial: 'A big social event today, unplanned',
      shower: 'No shower today',
      teeth: 'Teeth not brushed',
      food: 'No proper meal today',
      away: 'She’s away today',
    },
    swaps: 'Anchor swaps',
    swapsNote: 'An alternate swaps in only after forty-five days in which a phrase was never tapped across thirty answers, once per reading, never the middle. Logged here and in the export key.',
    swapsNone: 'No swap yet.',
    swapLine: '{name}, phrase {position}: “{from}” became “{to}” on {date}, after {answers} answers.',
  },
  brief: {
    title: 'This morning',
    starts: 'The brief starts after seven days of record: {d} so far.',
    today: 'Today, as you usually are: morning {m} · afternoon {a} · evening {e}',
    range: '{lo} to {hi}',
    yesterday: 'Yesterday: expected {expected}, read {actual}; {result}.',
    hit: 'within the range',
    miss: 'outside the range',
    yesterdayNone: 'Yesterday: no forecast to set beside what happened.',
    model: 'Model: {model}, the one that scored best on your past days. Ranges are its 20th to 80th past errors.',
    models: { sameBlock: 'same block, four weeks', weekdayBlock: 'same weekday and block', lastValue: 'the last time', blend: 'same block and same weekday, blended' },
    warning: 'A stretch may be starting: {under} of the last {of} blocks read under the expected range. The two evening chips: {chips} of the last three evenings. Necessities missed: {necessities} in three days.',
    whatIf: 'If you did nothing extra this evening: about {v}. An assumption the app has never verified.',
  },
  necessities: {
    title: 'Necessities today',
    note: 'A tap marks a miss; silence is not evidence. Never offered as a move, never celebrated. A setup move can target one.',
    shower: 'No shower today',
    teeth: 'Teeth not brushed',
    food: 'No proper meal today',
    missed: 'Missed',
  },
  weekly: {
    title: 'The weekly view',
    door: 'The weekly view',
    doorNote: 'The scorecard, the week ahead, best-days, the gap, what moved, what lasts, catalogue health, the extension prompt.',
    baseline: 'Baseline',
    shifted: 'Your baseline has shifted since {since}: the {before} days before averaged {beforeMean}, the {after} since {afterMean}, a difference of {diff} points, {t} standard errors apart.',
    steady: 'No shift in the baseline over the last {days} days: the cleanest split is {t} standard errors apart, under three.',
    baselineNone: 'Baseline change detection needs ten days with two logged blocks.',
    scorecard: 'Scorecard',
    hitRate: 'Forecast hit rate {rate} percent against a target of 60, over {n} day-ahead forecasts; average miss {miss} points.',
    hitRateNone: 'No day-ahead forecasts scored yet; they begin after fourteen days of record.',
    declared: 'Experiments declared {declared}, replicated {replicated}.',
    gaveBack: 'Check-ins that gave something back: {gaveBack} of {all}.',
    answering: 'Median answering time: morning {m}, afternoon {a}, evening {e}.',
    seconds: '{s} s',
    none: '—',
    ahead: 'The week ahead, as you usually are',
    aheadLine: '{day}: {expected} ({lo} to {hi})',
    aheadNone: 'The week ahead appears after fourteen days of record.',
    aheadCaption: 'Daily expected value with range (lower–upper).',
    best: 'Best-days',
    bestSilent: 'Silent until twenty days with two logged blocks: {days} so far.',
    bestNote: 'Your top tenth of days, {k} of {days}, and what was different.',
    control: 'What you control',
    notControl: 'What you don’t',
    diffLine: '{label}: {onBest} of {ofBest} best days, {onOthers} of {ofOthers} others',
    gapTitle: 'The gap',
    gapLine: 'Typical {typical} · good {good} · best {best}',
    gapOften: 'Good days {often} percent of {days}; the last one {ago} days ago.',
    gapAim: 'The app aims at the gap between typical and good.',
    gapNone: 'The gap appears after seven days with two logged blocks.',
    moved: 'What moved this week',
    movedReading: 'The reading: {thisWeek} this week against {lastWeek} last week ({delta}).',
    movedLine: '{reading}: {delta} steps',
    movedNone: 'Two weeks of record needed.',
    lasts: 'What lasts and what doesn’t',
    lastsLine: '{move}: held about {days} days after a run ({runs} runs)',
    lastsNone: 'Nothing yet: it takes three runs of three days.',
    rewardLine: '{reward}: first three {first} ({n}), later {later} ({m})',
    rewardNone: 'not enough record',
    lastsNote: 'Novelty lifts high and briefly; mastery lifts less and holds. The record will say whether that is true for you.',
    health: 'Catalogue health',
    healthLine: '{name}: {live} live, offered {offered}, done {done}',
    unreachable: 'unreachable: {blocker}',
    healthNote: 'A family is unreachable when no entry of it was a candidate in any situation of the last fortnight.',
    prompt: 'The extension prompt',
    promptNote: 'Written by the app from what you never take and which situations run short. No private item is in it. Copy it to a builder.',
    copy: 'Copy',
    copied: 'Copied',
  },
  evidence: {
    title: 'Evidence',
    observationsLine: '{n} effects on record · {weeks} weeks',
    intro: 'Every active card with its tier, counts and interval. Confirmatory claims rest on the coin-flip slice, tightened across every card active today, replicated after a dated declaration.',
    register: 'Facts are plain. Calculations carry a single rule on the left. Conclusions carry a double rule, and always their tier.',
    months: 'Three check-ins a day is about ninety observations a month across everything. Some answers take months; some stay uncertain. That is the honest shape of it.',
    cards: 'Cards',
    none: 'No cards yet. A card is written the first time a move is offered against an alternative.',
    against: '{move} against {alternative}',
    forTarget: 'for {target} over the {window}',
    tiers: { little: 'Little evidence', unclear: 'Unclear', promising: 'Promising', holdsUp: 'Holds up', unhelpful: 'Unhelpful here' },
    counts: 'done {done} of {doneAll}, the alternative {alternative} of {alternativeAll}, counting the coin-flip slice',
    interval: 'difference {diff} steps, {lo} to {hi}, at {level} percent',
    partly: 'partly, its own arm: {mean} steps ({n})',
    research: 'Research says {mean}',
    record: 'your record says {mean} ({n})',
    noRecord: 'your record says nothing yet',
    energy: 'Energy at the next block: {mean} steps ({n})',
    spill: 'Also seen, unclaimed: {list}',
    spillItem: '{reading} {mean} ({n})',
    decay: 'After a run of days, held about {days} days ({runs} runs)',
    declared: 'Declared {date}; since then {done} and {alternative}',
    replicated: 'replicated',
    notReplicated: 'not replicated yet',
    estimators: { adaptive: 'Estimator: adaptive weights over all the data (Hadad, Wager and Athey).', coinFlip: 'Estimator: the coin-flip slice, resampled.' },
    sliceLine: 'The coin-flip slice, kept running: {done} and {alternative} done; difference {diff}, {lo} to {hi}.',
    scheduled: 'Scheduled: offered a little more often here until its eight opportunities are in.',
    origins: { import: 'imported, to test', signFlip: 'a sign flip, tested on purpose', passive: 'a passive item', weight: 'a weight card', app: '' },
    card: 'Card {id} · written {date}',
    weights: 'Weight cards',
    equalWeights: 'equal weights',
    weightLine: 'Equal weights carried forward miss the next block by {equal} points; the proposed weights by {weighted}; difference {diff} ({lo} to {hi}) over {n} pairs.',
    weightNote: 'Weights stay equal until a weight card holds up. Phase 12 declares them.',
    weightsNone: 'A weight card is written after four weeks of full days.',
    eventsTitle: 'Evenings that carried an event',
    coolingTitle: 'Cooling off',
    coolingLine: '{n} evenings marked. The morning after read {with}, against {without} after evenings that started the same. Cooling off ran about {blocks} blocks ({events} events).',
    socialTitle: 'Big social days',
    socialLine: '{n} evenings marked. The morning after read {with}, against {without} after evenings that started the same. The recovery gap rides alongside the next evening’s move.',
    associationNote: 'An association, never a cause. Counts, never streaks. Capped at Promising.',
    privates: 'Private items',
    privateOff: 'Private items enter selection only when you turn that on under Settings → Moves. Off, nothing here is computed.',
    privateLine: '{name}: mornings after read {with}, against {without} after evenings that started the same ({n} and {m}). An alternative: {alternative}.',
    brings: 'What brings you back',
    bringsLine: '{move} · {n}',
    bringsNone: 'No return after three days away yet.',
    bringsNote: 'The moves done in the day before a Resume that followed three or more days away. A count, not a claim.',
    tagsTitle: 'What the tags have learned',
    tagLine: '{name}: research {research}, your record {record} ({n})',
    tagNone: 'nothing yet',
  },
  history: {
    title: 'History',
    count: '{n} offers',
    empty: 'No moves offered yet. Complete a check-in and one follows.',
    offer: 'Offer {id}',
    card: 'Card {id} · {window}',
    noCard: 'No card',
    outcome: 'Outcome {id}',
    noOutcome: 'No outcome yet',
    pending: 'Pending',
    unanswered: 'Not answered',
    skipped: 'Skipped',
    coinFlip: 'coin flip',
    pickup: 'before pickup',
    study: 'study night',
    step: 'your aim',
    unblock: 'unblocking your aim',
  },
  aims: {
    yourAims: 'Your aims',
    tonight: 'Tonight',
    differ: "Not the same as your step, on purpose. Tonight's move follows your reading; your step is yours.",
    same: "Tonight's move is your step.",
    kinds: { certification: 'The certification', person: 'A person', practice: 'A practice' },
    kindNotes: {
      certification: 'Its step is the next rung of the proof ladder, sized to one sitting.',
      person: 'Its step is one move from the people family, yours to keep or change.',
      practice: 'Its step is one practice from faith, movement or steadying, yours to keep or change.',
    },
    commitments: 'Your commitments',
    none: 'No commitments yet. Add one; there is nothing to type.',
    add: 'Add a commitment',
    addNote: 'Nothing to type. The step is pre-filled from the ladder or picked from the catalogue.',
    allAdded: 'All three kinds are in place.',
    pickStep: 'Pick the step',
    pickNote: 'One line sized to one sitting. Change it any time from Aims.',
    sized: '{n} min · sized to one sitting',
    resume: 'Resume',
    started: 'Started · asked at your next check-in',
    remove: 'Remove',
    changeStep: 'Change the step',
    protectedNote: "Held above the move on Now. Tonight's reading never pushes it aside; you always decide.",
    blocked: 'Last time: {why}. The offer removes the obstacle, never shrinks the aim:',
    blockedWhy: { noTime: 'no time', didntWant: "didn't want to", tired: 'tired', tooMuch: 'too much on', unsaid: 'not now, no reason given' },
    unblockStart: 'Do it',
    her: 'Her',
    herNote: 'Her skills from the checklists and your moments together, counts only.',
    ladder: 'The proof ladder',
    ladderNote: 'Six proofs per skill, counts only. A skill moves only by your tap: Done on its step, or the taps here.',
    follow: 'Follow-through',
    followNote: 'Counts only. Started and finished, across moves, steps and minimum wins.',
    followLine: '{started} started, {finished} finished',
    followMoves: 'Moves',
    followSteps: 'Steps',
    followWins: 'Minimum wins',
    becoming: 'Becoming',
    becomingNote: 'Your direction, shown back unchanged, and dated counts from what was marked done.',
    noDirection: 'No direction line yet. Settings → Your direction.',
    counts: { study: 'Study sessions resumed', conversations: 'Conversations started', timeWithHer: 'Time with your daughter', faith: 'Faith practices you chose' },
    countLine: '{n} · last {date}',
    countNone: 'None marked done yet',
    dataNote: 'Commitments, skills and marks are part of your record. Removing one keeps its record; nothing is graded.',
  },
  her: {
    title: 'Her',
    source: 'Skills from the {who} “Learn the Signs. Act Early.” milestone checklists for 4 years and 5 years, the {year} lists. Counts only: never a percentage, a bar, a grade or a comparison with other children.',
    moments: 'Moments with her',
    momentsNone: 'None counted yet.',
    momentsOne: '1 moment · {first}',
    momentsLine: '{n} moments · first {first} · last {last}',
    practiceDone: 'Practice moves done: {n} · last {last}',
    practiceNone: 'Practice moves done: none yet.',
    countMoment: 'Count a moment',
    skills: 'Her skills',
    noSkills: 'No skills on the list yet. Add one from the checklists; nothing to type.',
    addSkill: 'Add a skill from the checklists',
    addNote: 'Four areas, the lists for 4 and 5 years. Tap one to watch it.',
    rungNote: 'A rung moves only by your tap. A count never moves it.',
    note: 'Counts only: no percentage, no bar, no grade, no comparison with other children.',
    rungs: ['Not introduced', 'Practicing with Daddy', 'Needs support', 'Doing sometimes', 'Doing often'],
    noCount: 'No count yet',
    countsLine: 'Did it {did} · on her own {own} · a little help {some} · a lot of help {lots}',
    lastOn: 'last {day}',
    countOne: 'Count one',
    rung: 'Rung',
    remove: 'Remove',
    helpQuestion: 'How much help did she need?',
    help: { own: 'On her own', some: 'A little help', lots: 'A lot of help' },
    pickTitle: 'The checklists',
    by: 'By {age}',
    onList: 'On the list',
    addTap: 'Add',
  },
  ladder: {
    title: 'The proof ladder',
    intro: 'Each skill climbs six proofs. Counts only: no percentages, no bars, no readiness score.',
    skills: 'Skills',
    noSkills: 'No skills yet. Add the skills the certification proves, one line each, typed here, never shipped.',
    addSkill: 'Add a skill',
    skillPlaceholder: 'One skill',
    add: 'Add',
    up: 'Next rung',
    back: 'Back one',
    remove: 'Remove',
    rungs: ['Not started', 'Watched or read', 'Practiced', 'Built once', 'Broke and fixed', 'Explained from memory', 'Resume bullet'],
    steps: ['watch or read it', 'practise it', 'build it once', 'break it and fix it', 'explain it from memory', 'write the resume bullet'],
    what: [
      'One video or chapter on it, start to finish, notes closed.',
      'Do it once with the material open. Getting it wrong is the point.',
      'Make one small working thing with it, from nothing, no template.',
      'Break the thing you built on purpose, then fix it without looking anything up.',
      'Explain it out loud from memory, as if teaching, until it holds together.',
      'Write the one resume line this proves, with what you built and what it did.',
    ],
    countLine: '{n} at {rung}',
    emptyStep: 'With no skills on the ladder, the step is the catalogue’s own: write the exact next study step.',
  },
  movesTab: {
    historyNote: 'Every offer, its card, and what happened, as three separate records.',
    evidenceNote: 'Every active card with its tier, counts and interval; the tags; the weight card; the associations.',
    tiersNote: 'Tiers are computed, never typed. Confirmatory claims rest on the coin-flip slice; a move is never retired.',
  },
  data: {
    title: 'Data',
    export: 'Export',
    exportNote: 'Everything you recorded, as JSON and CSV, handed to the share sheet. The app sends nothing anywhere.',
    includePrivate: 'Include private items by name',
    exportButton: 'Export JSON and CSV',
    exporting: 'Preparing…',
    lastExport: 'Last export {when}.',
    neverExported: 'Not exported yet.',
    exportFailed: 'The share sheet did not open. Try again from the installed app.',
    importTitle: 'Import a hypothesis',
    importNote: 'An outside hypothesis enters only as a card to test, never as something to believe. Paste one line of JSON: move, alternative, target, context.',
    importPlaceholder: '{"move": "walk-ten", "alternative": "nap-ten", "target": "energy", "context": "afternoon"}',
    importButton: 'Add the card',
    importDone: 'Card written. It shows under Moves → Evidence and nowhere else.',
    importErrors: {
      notJson: 'That is not JSON.',
      fields: 'Four fields are needed: move, alternative, target, context.',
      move: 'The move is not in the catalogue.',
      alternative: 'The alternative is not in the catalogue (or "nothing").',
      target: 'The target must be one of the six ingredients.',
      context: 'The context must be morning, afternoon or evening.',
      same: 'The move and the alternative are the same.',
    },
    deleteTitle: 'Delete everything',
    deleteNote: 'Every check-in, win, private item and setting on this phone, and this app’s rows in your cloud copy when a token is set. Nothing comes back.',
    deleteCloudFirst: 'The cloud copy is deleted first. If it cannot be reached, nothing is deleted.',
    deleteCloudFailed: 'The cloud copy could not be reached, so nothing was deleted. Try again online, or remove the token under Cloud copy first.',
    deleteStart: 'Delete everything',
    deleteWord: 'delete',
    deletePrompt: 'Type {word} to confirm.',
    deleteConfirm: 'Delete it all',
    deleteCancel: 'Keep it',
  },
  settings: {
    checkins: 'Check-ins',
    depth: 'Depth',
    depthFull: 'Full',
    depthShort: 'Short',
    depthNote: 'Short asks mood, energy and stress in every block.',
    frequency: 'Frequency',
    freqThree: 'Three a day',
    freqTwo: 'Morning and evening',
    freqOne: 'Evening only',
    lowDemand: 'Low-demand mode',
    lowDemandNote: 'For rough weeks: short depth, evening only, one reminder, no move, no coin flips. Off restores what you had.',
    quiet: 'Quiet hours',
    quietFrom: 'From',
    quietTo: 'To',
    quietNote: 'No reminders in quiet hours.',
    reminders: 'Reminders',
    remindersOn: 'Remind me',
    reminderTime: '{block} reminder',
    remindersNote: 'One reminder per block, worded the same every time. None in quiet hours, none for a block already begun.',
    inAppNote: 'With the app open in the background it reminds you itself at these times. To be rung with the app closed, set up the ping.',
    remindersDenied: "Notifications are off for this app in the phone's settings.",
    remindersUnsupported: 'This browser offers no notifications here.',
    pushTitle: 'The ping',
    pushSetup: 'Set up the ping',
    pushCopy: 'Copy address',
    pushCopied: 'Copied',
    pushShow: 'Show address',
    pushHide: 'Hide address',
    pushUnsubscribe: 'Unsubscribe',
    pushSubscribedAt: 'Set up {when}.',
    pushChanged: 'The address changed. Copy it again and paste it to the builder.',
    pushUnsupported: 'This browser has no push here. Open the installed app on the phone.',
    pushNote:
      'A content-free ping arrives at 07:30, 13:00 and 19:30 (America/New_York), sent from your own repository. The worker on this phone decides whether to show anything. This address is the only thing that ever leaves the phone; it carries no content, and Unsubscribe kills it. Paste it to the builder once.',
    movesSection: 'Moves',
    offerFaith: 'Offer faith moves',
    offerFaithNote: 'Off hides the whole family with one tap. Nothing is counted either way.',
    privateInSelection: 'Use private items to pick moves',
    privateInSelectionNote: 'Off on a fresh install. On, an evening card says what the record associates with an item, like for like, and names an alternative. Never "don’t".',
    extras: 'Evening extras',
    extraWin: "Tomorrow's minimum win",
    extraCaffeine: 'Caffeine after midday',
    extraDinner: 'Late or heavy dinner',
    extraPrivate: 'Private log',
    extraFaith: 'Felt close to God today?',
    faithNote: 'Off stays off until you turn it on here. Never counted, never a streak.',
    more: 'More',
    dataRow: 'Data',
    dataRowNote: 'Export everything, or delete everything.',
    private: 'Private',
    privateNote: 'Items you name, measured, shown nowhere else unless you choose.',
    readingsRow: 'Readings and chips',
    readingsRowNote: 'Retirement proposals, chips that stopped appearing, anchor swaps.',
    wording: 'Wording',
    wordingNote: 'The 13 readings, their 65 phrases, and 48 alternates for your veto.',
    legend: 'Legend',
    legendNote: 'How facts, calculations and conclusions are told apart.',
    about: 'About',
    app: 'App',
    build: 'Build',
    builtAt: 'Built',
    run: 'Open the run that tested this build',
    runMissing: 'Built outside the pipeline, so there is no run to show.',
    testsOne: '{n} unit test passed before this build.',
    testsMany: '{n} unit tests passed before this build.',
    testsUnknown: 'Test count not recorded for this build.',
    data: 'Data',
    dataNote: 'The phone is the source of truth. A copy syncs to a database you control once you paste its token under Cloud copy; no other party ever receives it. Nothing else leaves the phone but the ping address, if you set one up, and whatever you choose to export.',
    cloudRow: 'Cloud copy',
    cloudRowNote: 'Paste the token once; the copy syncs on its own.',
    phase: 'Phase F of the build plan: fatherhood.',
  },
  private: {
    title: 'Private',
    note: 'Named here only. Part of your cloud copy like everything else, by your choice. Never in an export unless you tick them. Never in any document.',
    none: 'Nothing named yet.',
    placeholder: 'Name it',
    add: 'Add',
    remove: 'Remove',
    show: 'Show private items by name outside this screen',
  },
  cloud: {
    title: 'Cloud copy',
    intro: 'The phone is the source of truth. A copy of everything you record syncs to a database you control. No other party ever receives it.',
    url: 'Database',
    urlNote: 'A constant, not a secret. Shown so you can match it against your Turso dashboard.',
    token: 'Token',
    tokenPlaceholder: 'Paste the token once',
    tokenSet: 'Token stored on this phone.',
    tokenNote: 'Created in your Turso dashboard, pasted once, stored in this app’s storage on the phone. It never appears in source, tests, the pipeline or logs.',
    keep: 'Keep it',
    remove: 'Remove the token',
    status: 'Status',
    off: 'Sync is off until a token exists.',
    lastSync: 'Last sync {when}',
    never: 'Not synced yet',
    pending: '{n} pending',
    pendingNone: 'nothing pending',
    syncing: 'Syncing…',
    offline: 'Offline; changes wait here.',
    error: 'Last attempt did not go through: {error}. It retries on its own.',
    syncNow: 'Sync now',
    device: 'This phone',
    limit: 'One phone per app for now: local ids are numbered per device. A second phone needs string ids first.',
    restoreNote: 'On a fresh install, paste the token and the first sync restores everything.',
    tokenMissing: 'The token went missing from this phone on {when}. Paste it again; the first sync then pulls everything back.',
    lastSeen: 'last seen {when}',
    notKept: 'The token did not stay in the app’s database. Try again.',
    tokenLog: 'Token log',
    logSaved: 'Pasted in Settings.',
    logSavedNoMirror: 'Pasted in Settings. The phone’s second copy could not be written.',
    logSecondCopy: 'A second copy of the token was written to the phone’s local storage, and the whole history was checked against the cloud copy.',
    logLocalRestored: 'The phone’s second copy of the token was missing and was written again from the app’s database.',
    logDatabaseRestored: 'The app’s database had lost the token; it was written again from the phone’s second copy, and the whole history was pulled back.',
    logDisagreed: 'The two copies of the token disagreed; the more recently saved one was kept.',
    logMissing: 'The token is missing from both the app’s database and the phone’s second copy. Paste it again and the first sync pulls everything back.',
    logRemoved: 'Removed in Settings.',
  },
  legend: {
    title: 'Legend',
    intro: 'Three kinds of thing appear on screen, and they always look different.',
    facts: 'Facts',
    factsNote: 'What you tapped and when. Plain text.',
    calcs: 'Calculations',
    calcsNote: 'Numbers the app derives from facts, always with their recipe. Set off by a thin rule on the left; every chart carries its caption.',
    conclusions: 'Conclusions',
    conclusionsNote: 'What the app claims to have learned. Set off by a double rule on the left, and always with its evidence tier: Little evidence, Unclear, Promising, Holds up, Unhelpful here.',
    recipe: 'The reading out of 100',
    recipeNote:
      'Six readings have a clear better direction: mood, energy and focus up; stress, overwhelm and irritation down. Each phrase maps to 0, 25, 50, 75 or 100, reversed where lower is better. The reading is their equal-weight mean; every block asks all six, and a block missing any of them reads Incomplete, never a number. Weights stay equal until a learned weighting clears the bar in Phase 10.',
    stances: 'The five bands',
    stancesNote: '0 to 19 Empty · 20 to 39 Worn down · 40 to 59 Getting by · 60 to 79 Solid · 80 to 100 Firing. Descriptions of a state, never a verdict. From 80 the band’s name turns the accent; the number stays white.',
    context: 'Context',
    contextNote: 'Hunger, sleep, confidence, loneliness and social energy sit beside the reading. They never enter it.',
    silence: 'Silence',
    silenceNote: 'An unanswered question shows Not logged yet. It changes no number, fills no gap on a chart, and prompts no catch-up.',
  },
  wording: {
    intro: 'Five phrases per reading, least to most. You pick a phrase, never a number.',
    sets: 'Morning asks all 13. Afternoon asks seven: mood, irritation, energy, hunger, stress, focus, overwhelm. Evening asks those and loneliness. Every block feeds all six ingredients of the reading.',
    alternatesNote: 'Under each phrase but the middle, one pre-written alternate for your veto. A swap happens only in Phase 12, once per reading, never the middle, logged and dated.',
    alternate: 'or: {phrase}',
    swapped: 'swapped in on {date}; was “{from}”',
  },
  reminders: {
    body: 'Time for your {block} check-in.',
    quiet: 'Nothing due right now.',
  },
} as const
