// Every string a person can read in the app lives here (readings and their anchor phrases
// live in readings.json, moves in catalogue.json), so one test can check all of them against
// the plan's rule: a reading, never a verdict.
export const copy = {
  caffeine: {
    title: 'Caffeine since your last check-in',
    titleMorning: 'Caffeine so far today',
    factLabel: 'Caffeine',
    bands: { 1: 'Under 100 mg', 2: '100–199 mg', 3: '200–299 mg', 4: '300+ mg' },
    legacy: 'Recorded before amounts: caffeine, amount unknown.',
    onBoard: 'caffeine on board',
    anyAmount: 'Any amount',
    under: 'Under {mg} mg',
    orMore: '{mg} mg or more',
    between: '{lo}–{hi} mg',
    windows: { morning: 'Morning only', afternoon: 'Afternoon', evening: 'Evening' },
    windowsAny: 'Any window',
    or: ' or ',
    shorterHours: 'sleep read about {minutes} minutes shorter',
    lowerQuality: 'sleep quality read {q} of a step lower',
    ev: {
      title: 'Caffeine',
      habit: 'Reported on {reported} of the last 28 days. Usual morning band: {usual}. Shown and left untapped: {untapped}, which is none reported, never a confirmed none.',
      usualNone: 'none yet',
      byDayBand: 'The next night, by the day’s reported amount',
      byLatestWindow: 'The next night, by the last window with 100 mg or more',
      byMorningBand: 'That afternoon, by the morning’s amount',
      reported: 'The same check-in: caffeine reported, against shown and none reported',
      nothingYet: 'Nothing reported yet.',
      groupSleep: '{label}: {n} {unit} · sleep about {hours} h · quality {quality} of 5',
      groupReading: '{label}: {n} {unit} · read {value}',
      groupCount: '{label}: {n} {unit}',
      units: { day: 'day', days: 'days', morning: 'morning', mornings: 'mornings', checkIn: 'check-in', checkIns: 'check-ins', window: 'window', windows: 'windows' },
      sleepDiff: 'Like for like on the sleep the day began with, the last group against the first: {parts}. {standing}.',
      sleepMinutes: 'sleep {minutes} min',
      sleepQuality: 'quality {quality} of a step',
      and: ' and ',
      unmatchedSleep: 'No day in one group began on the same sleep as a day in the other, so nothing is compared like for like yet.',
      unmatchedMorning: 'No morning in one group began on the same sleep as one in the other, so nothing is compared like for like yet.',
      unmatchedTime: 'The two groups share no time of day, so nothing is compared like for like yet.',
      readingDiff: 'Like for like, the last group against the first: {diff} points. {standing}.',
      tooFew: 'One group so far: comparing needs two groups of at least five.',
      none: 'No difference is showing; self-reported sleep is known to miss caffeine’s effect.',
      noneReading: 'No difference is showing.',
      reportedLabel: 'Caffeine reported',
      untappedLabel: 'None reported',
      droppedMornings: 'Untapped mornings are left out ({n}): with caffeine reported on most of the last 28 days, an untapped morning is more likely forgotten than empty.',
      withdrawal: 'Reported on most days: part of a same-check-in difference may be withdrawal on the check-ins without it, not a lift on the ones with it.',
      note: 'Associations in your record, nothing more. Counts are shown; a group under five shows nothing and merges with the one beside it; capped at Promising, and Promising only from fifteen in each group across six weeks.',
    },
    help: 'Only if you had some; with none, leave it. Pick the closest band: the same coffee can land in either of two. Under 100: tea, a cola, one espresso, a small energy drink (8.4 oz). 100–199: a regular coffee (8 to 12 oz), two espressos, a 16 oz Monster. 200–299: a large coffee (16 oz), cold brew, a Celsius, most pre-workouts. 300 or more: a Bang or a Reign, two large coffees.',
  },
  people: {
    contexts: { weekday: 'Weekday {blocks} at home', office: 'Office-day {blocks}', weekend: 'Weekend {blocks}' },
    blocks: { morning: 'mornings', afternoon: 'afternoons', evening: 'evenings' },
    carried: '{context} have carried an in-person rep {times}.',
    once: 'once',
    times: '{n} times',
    uncovered: '{context} have carried an in-person rep {times}, and your week’s shape never counts people around then, so in-person reps are not offered there. If people usually are, the week in Settings or today’s chips can say so.',
    healthTitle: 'People around',
    healthNone: 'Every context where you have done an in-person rep is one your week’s shape counts as people around.',
  },
  when: { today: 'today', yesterday: 'yesterday', daysAgo: '{n} days ago' },
  appName: 'Life Mirror',
  tabs: {
    now: 'Now',
    mirror: 'Mirror',
    moves: 'Moves',
    aims: 'Aims',
    settings: 'Settings',
  },
  blocks: {
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
  },
  bands: {
    empty: 'Empty',
    wornDown: 'Worn down',
    gettingBy: 'Getting by',
    solid: 'Solid',
    firing: 'Firing',
  },
  now: {
    notLogged: 'Not logged yet',
    checkIn: 'Check in',
    continue: 'Continue',
    logged: 'Logged {time}',
    incomplete: '{n} of {total} answered',
    from: 'From {time}',
    earlier: 'Earlier',
  },
  today: {
    now: 'Open now',
    logged: 'Logged',
    checkIn: 'Check in · {block}',
    continue: 'Continue · {block}',
    context: 'Today, if different',
    awayToday: "She's away today",
    studyNight: 'Study night',
    notStudyNight: 'Not a study night today',
    officeToday: 'At the office today',
    homeToday: 'Working from home today',
    note: 'Statements, not commands. Only exceptions to the week live here; they change today alone.',
  },
  study: {
    fact: 'Study night',
    kept: '{kept} kept of {total}',
    eyebrow: 'Study night',
    sized: '{n} min · sized to one sitting',
    start: 'Start it',
    notNow: 'Not now',
    whyQuestion: 'One optional tap: why not?',
    reasons: { tired: 'Tired', tooMuch: 'Too much on', noTime: 'No time', didntWant: "Didn't want to" },
    leave: 'Leave it',
    said: 'You said {reason}. Tonight {evidence}.',
    evidence: '{reading} reads {phrase}',
    smaller: '{name} instead?',
    smallerMinutes: '{n} minutes of it instead?',
    smallest: 'This is already the smallest version. It stays on offer; you decide.',
    patternWeekday: "You've said {reason} the last {n} {weekday}.",
    patternAll: "You've said {reason} the last {n} study nights.",
    continue: 'Continue',
    note: 'You decide. The app never overrides you; it only never lets the skip be silent.',
  },
  reading: {
    recipe: '{used} of {total} ingredients · {weights}',
    equalWeights: 'equal weights',
    learnedWeights: 'learned weights, from a weight card that held up',
    at: '{block} {time}',
    atDay: '{day}, {block} {time}',
    incomplete: 'Incomplete',
    soFar: '{n} of {total} ingredients answered so far · no number until all six are in',
    none: 'Not logged yet',
    noneNote: 'The reading out of 100 appears after a completed check-in.',
    scaleEmpty: 'The scale from 0 to 100, no reading yet',
    context: 'Context',
    today: 'Today so far',
    pastDay: '{day}',
  },
  direction: {
    title: 'Your direction',
    ask: 'One line about where you are going. Yours, kept with your record, shown back to you later. Asked once; change it any time in Settings.',
    placeholder: 'One line',
    save: 'Keep it',
    notNow: 'Not now',
    note: 'Nothing here goes anywhere but your own record.',
    settingsNote: 'Shown back to you at the moments that matter. Never counted, never graded.',
    edit: 'Your direction',
  },
  week: {
    title: 'The week',
    note: 'The shape of your week, known from day one, no learning needed. A move that needs daylight waits for your daylight hours; one that needs quiet waits for a day at home.',
    churchDay: 'Church day',
    none: 'None',
    livesWithMe: 'She lives with me',
    livesWithMeNote: "The constant. The exception is one chip inside the check-in: She's away today.",
    studyNights: 'Study nights',
    officeDays: 'Office days',
    daycareDays: 'Daycare days',
    daylightFrom: 'Daylight from',
    daylightTo: 'Daylight until',
    pickup: 'Daycare pickup',
    pickupOn: 'There is a pickup',
    pickupTime: 'Pickup time',
    soloUntil: 'Her bedtime; solo hours run until then',
    days: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
  },
  win: {
    today: 'Minimum win today',
  },
  checkin: {
    progress: '{block} · {n} of {total}',
    back: 'Back',
    close: 'Close',
    clear: 'Clear this answer',
  },
  summary: {
    logged: '{block} · logged {time}',
    incomplete: '{block} · incomplete',
    readings: 'Readings',
    extras: 'Extras',
    changeExtras: 'Change the extras',
    notLogged: 'Not logged yet',
    finishFirst: 'Finish the readings and this card says what changed.',
    done: 'Done',
    delete: 'Delete this check-in',
    deleteConfirm: 'Tap again to delete it',
    usual: 'Usually {expected} ({lo} to {hi}) at this time.',
  },
  since: {
    heading: 'Since {when}',
    first: 'Your first reading. From the next one, this card says what changed.',
    sameDay: 'this {block}',
    yesterday: 'yesterday {block}',
    weekday: '{weekday} {block}',
    date: '{date}, {block}',
    up: '{name} up {amount}',
    down: '{name} down {amount}',
    unchanged: 'Unchanged: {list}',
    nothingShared: 'Nothing to compare with the last check-in.',
  },
  amounts: {
    step: ['one step', 'two steps', 'three steps', 'four steps'],
    band: ['one band', 'two bands', 'three bands', 'four bands'],
  },
  extras: {
    title: 'Evening extras',
    note: 'All optional. One tap each.',
    yesterdayWin: "Yesterday's minimum win",
    winOutcome: { done: 'Done', partly: 'Partly', no: 'No' },
    tomorrowWin: "Tomorrow's minimum win",
    winPlaceholder: 'One line, sized to one sitting',
    winSet: 'Set for tomorrow.',
    caffeine: 'Caffeine',
    dinner: 'Late or heavy dinner',
    faith: 'Felt close to God today?',
    faithOff: 'Turn this question off',
    private: 'Private log',
    privateLogged: '{n} logged',
    yes: 'Yes',
    logged: 'Logged',
    done: 'Done',
    chips: 'How today landed',
    nothingLanded: 'Nothing landed today',
    hardToSeePoint: 'Hard to see the point today',
    chipFirst: 'First time recorded.',
    chipTimes: '{n} times before. The morning after read {mean}, against {without} after evenings that started the same ({k} and {m}).',
    chipTimesNoNext: '{n} times before. No readings from the morning after yet.',
    chipUnmatched: '{n} times before. The morning after read {mean} ({k}); nothing yet to set it against.',
    coolingOff: 'Something rattled me today',
    bigSocial: 'A big social event today, unplanned',
    napped: 'Napped today',
    heavyCaffeine: 'Heavy caffeine this morning',
    morningChips: 'This morning',
    morningNote: 'One statement about the morning, answered from your record: the afternoons after mornings like it. Dose and timing stay out; this is one tap.',
    morningTimesNoNext: '{n} mornings marked before; no afternoon logged after one yet.',
    morningUnmatched: '{n} mornings marked before. The afternoon read {mean} ({k}); nothing to set it against yet.',
    morningTimes: '{n} mornings marked before. The afternoon read {mean}, against {without} after mornings that started the same ({k} and {m}).',
    coolingAnswer: 'Cooling off ran about {blocks} blocks after the last {events}.',
    recoveryNote: 'The recovery gap rides alongside tomorrow evening’s move, as it does after your church day.',
    chipDirection: 'Your direction: {line}',
    noteLabel: 'Anything the app has no question for',
    notePlaceholder: 'One line. The brain reads your last few notes.',
  },
  mirror: {
    today: 'Today',
    week: 'The week',
    heatmap: 'Days by blocks',
    together: 'Moves together',
    overlay: 'Overlay a context reading',
    overlayNone: 'Reading only',
    todayCaption: '{n} of 3 blocks logged · the reading out of 100 by block · an overlay shows a context reading on the same scale',
    weekCaption: 'Seven days · each dot one block · a gap is Not logged yet',
    heatCaption: 'Brighter is higher · an empty outline is Not logged yet · {days} days',
    togetherNote: 'Moving together is not causing.',
    togetherCaption: 'Rank correlation between two readings across the check-ins where both were answered. Pairs with fewer than {min} shared check-ins are not shown.',
    togetherEmpty: 'Nothing to show yet: no pair of readings has {min} shared check-ins.',
    shared: 'n {n}',
    empty: 'Nothing logged yet. The mirror draws from your check-ins.',
  },
  catalogue: {
    paths: {
      title: 'Paths',
      note: 'Two paths, each a staged curriculum of reps, with your Green. The Social path is wired: add it under Aims, and its own reps are offered through its row alone. The Partner path is not wired yet; its reps marked proposed are offered nowhere until it is.',
      stage: 'Stage {n} · {name}',
      notProgress: 'Not progress',
      moves: { counts: 'Moves by the rule', 'counts or a date': 'Moves by the rule, or when you say you have a date', declared: 'Moves only when you declare it' },
      advances: 'moves the stage',
      movesNothing: 'moves no stage',
      where: 'Where',
      cue: 'Attention on',
      crutch: 'Drop',
      rule: 'How a stage is reached',
      counted: 'Counted',
      neverCounted: 'Never counted, stored or asked',
      excluded: 'Left out, and why',
      settingsTitle: 'Kinds of setting',
      channel: 'Channel',
      channelOff: 'off until you turn it on',
      acts: 'Private notes and checks',
      questions: 'The questions',
      helpOnYes: 'A yes shows the help.',
      help: 'The help the app shows itself',
      parents: 'For a parent',
      evidence: 'The evidence',
      evidenceNote: 'Claim cards, each source verified at Crossref: drafts until their path is wired, and the disputed ones are never cited.',
      draft: 'draft, admitted when its path is wired',
      disputed: 'disputed, never cited',
      admitted: 'admitted',
      onPath: '{path} path, stage {n}',
      settingNames: { recurring: 'a recurring place', errand: 'an errand', group: 'a group', oneToOne: 'one to one', remote: 'a call or a message', solo: 'on your own' },
    },
    title: 'The catalogue',
    count: '{n} moves · {proposed} proposed',
    read: 'Read the catalogue',
    readNote: 'Every move, with its source. Read it all, then veto by name.',
    intro: 'Every move the app may offer, with where it comes from and how strong that evidence is, what it takes and what it costs to be given, its tags, its starting belief, what it should move and over what window, what it never sits alongside, and what it counts toward.',
    strengthNote: 'Strength of evidence: strong means meta-analyses or several trials; moderate a good trial or review; thin a small study or evidence for something adjacent; practice common advice, untested.',
    vetoNote: 'Yellow names entries, tags, beliefs or alternates to cut or reword. Green wires the proposals; until then nothing here changes what is offered.',
    minutes: '{n} min',
    noTime: 'No time, a decision',
    effort: 'effort to start {level}',
    efforts: { low: 'low', medium: 'medium', high: 'high' },
    needsLabel: 'needs {needs}',
    needsNothing: 'nothing',
    needs: { outdoors: 'outdoors', kit: 'kit', anotherPerson: 'another person', freeHour: 'a free hour', daylight: 'daylight', quiet: 'quiet' },
    shouldMove: 'Should move',
    windows: { nextBlock: 'next block', laterToday: 'later that day', evening: 'evening', nextMorning: 'next morning', sevenDays: 'seven days' },
    tags: 'Tags',
    tagNames: { outdoors: 'outdoors', withPeople: 'with people', short: 'short', lowEffort: 'low effort', pleasure: 'pleasure', mastery: 'mastery', connection: 'connection', intensity: 'intensity' },
    intensity: 'intensity {level}',
    costLabel: 'cost to assign {level}',
    prior: 'Starting belief',
    priorLine: '{target} {arrow} by about {effect} of a step over the {window}',
    effectWords: { '0': 'no change, until your record says', '0.1': 'a tenth', '0.2': 'a fifth', '0.3': 'a third', '0.4': 'four tenths', '0.5': 'half' },
    proposed: 'Proposed',
    proposedNote: 'read and veto; joins the candidates at Green',
    pathProposedNote: 'Green given; joins the candidates when its path is wired',
    pathOnly: 'Offered through its path’s row alone, never by the day’s draw',
    parkProposed: 'Proposed to park',
    parked: 'Parked · shown here, never offered',
    standingSince: 'Set up on {date}',
    cameUndone: 'It came undone',
    ladderRung: 'rung {n} of the participation ladder',
    setupKinds: {
      lateness: 'a setup for chronic lateness',
      friction: 'removes a step before a move, for good',
      appointment: 'closes an avoided task, for good',
      default: 'a default that holds without reminders',
      necessity: 'a setup whose target is a necessity: {necessity}',
    },
    necessities: { food: 'food', teeth: 'teeth', shower: 'the shower' },
    passiveProposed: 'a passive item, riding alongside a move',
    learnedTitle: 'Learned tags and their starting beliefs',
    learnedNote: 'The app estimates each tag’s effect from your record, starting from these. No more learned tags than these.',
    filterTitle: 'Filter tags',
    filterNote: 'These only select. They are never learned.',
    researchTitle: 'The research the layer rests on',
    researchNote: 'Read before wiring: what each body of work contributes as entries, as tags, and as the wording of the two evening chips.',
    contributes: 'What it contributes',
    chipsLabel: 'The two chips',
    extensionTitle: 'The extension prompt, as the app will write it',
    tradesTitle: 'Proposed trades',
    wiringLabel: 'What Green wires',
    when: 'When',
    countsToward: 'counts toward',
    counters: { study: 'study', conversations: 'conversations', timeWithHer: 'time with her', faith: 'faith', finishing: 'finishing' },
    notAlongside: 'Not alongside',
    standsInFor: 'Stands in for',
    strengths: { strong: 'Strong evidence', moderate: 'Moderate evidence', weak: 'Thin evidence', practice: 'Practice, untested' },
  },
  move: {
    title: 'One small move',
    pickupTitle: 'Before pickup',
    nothing: 'Nothing today',
    nothingWhat: 'On purpose. Nothing extra this block; the record will show what that does.',
    why: 'Why this',
    evidence: 'Evidence for you',
    testing: 'Testing',
    whyNot: 'Why not that',
    whyLine: '{target} is your lowest reading right now. This should move it {arrow} over the {window}.',
    whyNothing: '{target} is your lowest reading right now. Nothing extra is one of the candidates, so the record can say what doing nothing does.',
    whyPickup: 'Its only job is arriving at pickup with something left.',
    evidenceLine: 'offered {n} in this situation, done {done}, partly {partly}.',
    once: 'once',
    twice: 'twice',
    nTimes: '{n} times',
    tierLittle: 'Little evidence',
    testingLine: '{move} against {alternative}, for {target} over the {window}. Card {id}, written {date}. A worthwhile change is one step.',
    testingNone: 'No alternative to test against in this situation yet.',
    coinFlip: 'This offer was a coin flip, so honest claims survive.',
    whyNotLine: 'Not {move}: {reason}.',
    whyNotReasons: {
      draw: 'the draw favoured this one today',
      coinFlip: 'this offer was a coin flip',
      observed: 'bedtime itself is observed, never offered',
      passive: 'it rides alongside a move rather than being one',
      study: 'study is offered at the evening check-in on study nights',
      schedule: 'it is not on today, by your week',
      block: 'it does not fit this block',
      hidden: 'its family is hidden',
      target: 'it does not move your lowest reading',
      band: 'your reading rules out its effort right now',
      offeredToday: 'it was offered today already',
      conflict: 'it sits badly with something done or offered today',
      rung: 'it is a harder rung than the readings allow',
      proposed: 'it is proposed, not yet wired',
      parked: 'it is parked',
      noTime: 'you said no time for something this long in this block this week',
      standing: 'you set this up already; if it came undone, say so on its catalogue entry',
      daylight: 'it needs daylight and the day has none left',
      quiet: 'it needs quiet and you are at the office',
      daycare: 'she is at daycare through this block',
      asleep: 'she is asleep by now',
      people: 'it needs someone there in person, and today’s shape puts nobody around in this block',
    },
    alongside: 'Alongside',
    skip: 'Skip · show the next',
    done: 'Done',
    doneLine: '{name} · {state} · {time}',
    hideFaith: 'Hide faith moves',
    pending: 'Asked at your next check-in.',
    happened: 'What happened',
    passedOver: 'Passed over at the next check-in.',
    none: 'Log a check-in and one small move follows.',
    hidden: 'Moves stay hidden while Low-demand mode is on.',
    privateInline: 'Your record: evenings with {name} logged, the morning after read {with} against {without} after evenings that started the same ({n} and {m}). An alternative: {alternative}.',
    knows: 'How much it knows: {weeks} weeks of record. Offers are still drawn evenly from what fits, low starting effort first; each offer now draws from research corrected by your record, recent days weighing more; nothing here is a claim until its card says so.',
  },
  ask: {
    title: 'Last time, one small move',
    titlePickup: 'Before pickup, last time',
    titleStep: 'Your aim, last time',
    titleUnblock: 'Unblocking, last time',
    question: 'Did you do it?',
    questionNothing: 'Did you keep it to nothing extra?',
    skip: 'Not now',
    whyQuestion: 'One optional tap: why not?',
    why: { noTime: 'No time', didntWant: "Didn't want to" },
    whySkip: 'Leave it',
    passiveQuestion: 'And {item}?',
    passiveDone: 'Happened',
    passiveNo: "Didn't",
    note: 'One tap. What happened is recorded apart from what was offered.',
  },
  readingsScreen: {
    title: 'Readings and chips',
    row: 'Readings and chips',
    rowNote: 'Retirement proposals, decided by you; chips that stopped appearing; anchor swaps.',
    proposals: 'Retirement proposals',
    proposalsNote: 'A context reading is proposed for retirement only when both conditions hold on your record: it adds no real distinction, and no predictive value. Never automatic; you decide. An ingredient is never proposed.',
    none: 'No proposal. Every reading is earning its place on the record so far.',
    twin: '{name} moves with {other}: rank correlation {r} over {n} shared check-ins.',
    flat: '{name} sits on the same phrase {share} percent of the time over {n} answers.',
    prediction: 'It foretells the next block’s reading no better than nothing: correlation {r} over {n} pairs.',
    retire: 'Retire it',
    keep: 'Keep it for now',
    retired: 'Retired readings',
    retiredNone: 'None.',
    bringBack: 'Bring it back',
    chips: 'Chips',
    chipsNote: 'A chip you never tap stops appearing after thirty logged evenings. One tap here brings it back.',
    chipOn: 'appearing · last tapped {when}',
    chipNever: 'appearing · never tapped, {n} check-ins so far',
    chipRetired: 'stopped after {n} check-ins without a tap',
    chipNames: {
      nothingLanded: 'Nothing landed today',
      hardToSeePoint: 'Hard to see the point today',
      coolingOff: 'Something rattled me today',
      bigSocial: 'A big social event today, unplanned',
      napped: 'Napped today',
      shower: 'No shower today',
      teeth: 'Teeth not brushed',
      food: 'No proper meal today',
      away: 'She’s away today',
      caffeine: 'Caffeine',
    },
    swaps: 'Anchor swaps',
    swapsNote: 'An alternate swaps in only after forty-five days in which a phrase was never tapped across thirty answers, once per reading, never the middle. Logged here and in the export key.',
    swapsNone: 'No swap yet.',
    swapLine: '{name}, phrase {position}: “{from}” became “{to}” on {date}, after {answers} answers.',
  },
  brief: {
    title: 'Since last night',
    starts: 'The brief starts after seven days of record: {d} so far.',
    lastNight: 'Last night carried {event}. Mornings after evenings like it have read {with}, against {without} after evenings that started the same ({n}).',
    lastNightFirst: 'Last night carried {event}: the first time recorded, so nothing to set this morning against yet.',
    lastNightEvents: {
      dinner: 'a late or heavy dinner',
      caffeine: 'caffeine reported at the evening check-in',
      coolingOff: 'something that rattled you',
      bigSocial: 'a big social day',
      napped: 'a nap',
      nothingLanded: 'a day when nothing landed',
      hardToSeePoint: 'a day when it was hard to see the point',
      necessity: 'a necessity missed',
      churchDay: 'the church day',
      workout: 'a workout',
    },
    yesterday: 'Yesterday: expected {expected}, read {actual}; {result}.',
    hit: 'within the range',
    miss: 'outside the range',
    yesterdayNone: 'Last night carried nothing the record can set this morning against.',
    steady: 'Steady: {inside} of the last {of} blocks read inside their usual range.',
    move: 'Yesterday, {name}: {arm}. {target} read {steps} of a step {dir} your usual this morning. One reading, not a finding.',
    moveNothing: 'Yesterday you kept to nothing extra, on purpose. {target} read {steps} of a step {dir} your usual this morning. One reading, not a finding.',
    above: 'above',
    under: 'under',
    models: { sameBlock: 'this time of day over the last four weeks', weekdayBlock: 'this weekday at this time of day', lastValue: 'the last time you logged this time of day', blend: 'this time of day and this weekday, blended' },
    warning: 'A stretch may be starting: {under} of the last {of} blocks read under the expected range. The two evening chips: {chips} of the last three evenings. Necessities missed: {necessities} in three days.',
    whatIf: 'If you did nothing extra this evening: about {v}. An assumption the app has never verified.',
  },
  necessities: {
    title: 'Necessities today',
    note: 'A tap marks a miss; silence is not evidence. Never offered as a move, never celebrated. A setup move can target one.',
    shower: 'No shower today',
    teeth: 'Teeth not brushed',
    food: 'No proper meal today',
    missed: 'Missed',
  },
  weekly: {
    title: 'The weekly view',
    door: 'The weekly view',
    doorNote: 'The scorecard, the week ahead, best-days, the gap, what moved, what lasts, catalogue health, the extension prompt.',
    baseline: 'Baseline',
    shifted: 'Your baseline has shifted since {since}: the {before} days before averaged {beforeMean}, the {after} since {afterMean}, a difference of {diff} points, {t} standard errors apart.',
    steady: 'No shift in the baseline over the last {days} days: the cleanest split is {t} standard errors apart, under three.',
    baselineNone: 'Baseline change detection needs ten days with two logged blocks.',
    scorecard: 'Scorecard',
    hitRate: 'Forecast hit rate {rate} percent against a target of 60, over {n} day-ahead forecasts; average miss {miss} points.',
    hitRateNone: 'No day-ahead forecasts scored yet; they begin after fourteen days of record.',
    declared: 'Experiments declared {declared}, replicated {replicated}.',
    gaveBack: 'Check-ins that gave something back: {gaveBack} of {all}.',
    answering: 'Median answering time: morning {m}, afternoon {a}, evening {e}.',
    seconds: '{s} s',
    none: '—',
    ahead: 'The week ahead, as you usually are',
    aheadLine: '{day}: {expected} ({lo} to {hi})',
    aheadNone: 'The week ahead appears after fourteen days of record.',
    aheadCaption: 'Daily expected value with range (lower–upper).',
    model: 'Expected from {model}, the model that scored best on your past days. The range is where six in ten past days landed against it.',
    best: 'Best-days',
    bestSilent: 'Silent until twenty days with two logged blocks: {days} so far.',
    bestNote: 'Your top tenth of days, {k} of {days}, and what was different.',
    control: 'What you control',
    notControl: 'What you don’t',
    controlNone: 'Nothing you control differs between your best days and the others yet.',
    notControlNone: 'Nothing outside your control differs between your best days and the others yet.',
    diffLine: '{label}: {onBest} of {ofBest} best days, {onOthers} of {ofOthers} others',
    gapTitle: 'The gap',
    gapLine: 'Typical {typical} · good {good} · best {best}',
    gapOften: 'Good days {often} percent of {days}; the last one {ago}.',
    gapAim: 'The app aims at the gap between typical and good.',
    gapNone: 'The gap appears after seven days with two logged blocks.',
    moved: 'What moved this week',
    movedReading: 'The reading: {thisWeek} this week against {lastWeek} last week ({delta}).',
    movedLine: '{reading}: {delta} steps',
    movedNone: 'Two weeks of record needed.',
    lasts: 'What lasts and what doesn’t',
    lastsLine: '{move}: held about {days} days after a run ({runs} runs)',
    lastsNone: 'Nothing yet: it takes three runs of three days.',
    rewardLine: '{reward}: first three {first} ({n}), later {later} ({m})',
    rewardNone: 'not enough record',
    lastsNote: 'Novelty lifts high and briefly; mastery lifts less and holds. The record will say whether that is true for you.',
    health: 'Catalogue health',
    healthLine: '{name}: {live} live, offered {offered}, done {done}',
    unreachable: 'unreachable: {blocker}',
    deadLine: 'never offerable: {moves}',
    healthNote: 'A family is unreachable when no entry of it was a candidate in any situation of the last fortnight. A move is never offerable when no situation at all admits it, whatever the day.',
    prompt: 'The extension prompt',
    promptNote: 'Written by the app from what you never take and which situations run short. No private item is in it. Copy it to a builder.',
    copy: 'Copy',
    copied: 'Copied',
  },
  evidence: {
    title: 'Evidence',
    observationsLine: '{n} effects on record · {weeks} weeks',
    intro: 'Every active card with its tier, counts and interval. Confirmatory claims rest on the coin-flip slice, tightened across every card active today, replicated after a dated declaration.',
    register: 'Facts are plain. Calculations carry a single rule on the left. Conclusions carry a double rule, and always their tier.',
    months: 'Three check-ins a day is about ninety observations a month across everything. Some answers take months; some stay uncertain. That is the honest shape of it.',
    cards: 'Cards',
    none: 'No cards yet. A card is written the first time a move is offered against an alternative.',
    against: '{move} against {alternative}',
    forTarget: 'for {target} over the {window}',
    tiers: { little: 'Little evidence', unclear: 'Unclear', promising: 'Promising', holdsUp: 'Holds up', unhelpful: 'Unhelpful here' },
    counts: 'done {done} of {doneAll}, the alternative {alternative} of {alternativeAll}, counting the coin-flip slice',
    interval: 'difference {diff} steps, {lo} to {hi}, at {level} percent',
    partly: 'partly, its own arm: {mean} steps ({n})',
    research: 'Research says {mean}',
    record: 'your record says {mean} ({n})',
    noRecord: 'your record says nothing yet',
    energy: 'Energy at the next block: {mean} steps ({n})',
    spill: 'Also seen, unclaimed: {list}',
    spillItem: '{reading} {mean} ({n})',
    decay: 'After a run of days, held about {days} days ({runs} runs)',
    declared: 'Declared {date}; since then {done} and {alternative}',
    replicated: 'replicated',
    notReplicated: 'not replicated yet',
    estimators: { adaptive: 'Estimator: adaptive weights over all the data (Hadad, Wager and Athey).', coinFlip: 'Estimator: the coin-flip slice, resampled.' },
    sliceLine: 'The coin-flip slice, kept running: {done} and {alternative} done; difference {diff}, {lo} to {hi}.',
    scheduled: 'Scheduled: offered a little more often here until its eight opportunities are in.',
    origins: { import: 'imported, to test', signFlip: 'a sign flip, tested on purpose', passive: 'a passive item', weight: 'a weight card', app: '' },
    passiveLine: '{n} days it rode alongside and was done: {target} the next morning read {with}, against {without} after evenings that started the same ({k} and {m}).',
    nothingTitle: 'Nothing today',
    nothingLine: 'Offered {offered} times, done {done}, skipped {skipped}. Kept to, it is measured like any move over the next block.',
    card: 'Card {id} · written {date}',
    weights: 'Weight cards',
    equalWeights: 'equal weights',
    weightLine: 'Equal weights carried forward miss the next block by {equal} points; the proposed weights by {weighted}; difference {diff} ({lo} to {hi}) over {n} pairs.',
    weightNote: 'Weights stay equal until a weight card, declared after four weeks of full days, holds up on fourteen more.',
    weightsNone: 'A weight card is written after four weeks of full days.',
    eventsTitle: 'Evenings that carried an event',
    coolingTitle: 'Cooling off',
    coolingLine: '{n} evenings marked. The morning after read {with}, against {without} after evenings that started the same. Cooling off ran about {blocks} blocks ({events} events).',
    socialTitle: 'Big social days',
    socialLine: '{n} evenings marked. The morning after read {with}, against {without} after evenings that started the same. The recovery gap rides alongside the next evening’s move, and the evening after your church day.',
    caffeineTitle: 'Heavy caffeine mornings, before amounts',
    caffeineLine: '{n} mornings marked. The afternoon read {with}, against {without} after mornings that started the same.',
    workoutTitle: 'Workout days',
    workoutLine: '{n} days with a finished workout, read from your other app. The evening read {with}, against {without} on days that started the same.',
    associationNote: 'An association, never a cause. Counts, never streaks. Capped at Promising.',
    privates: 'Private items',
    privateOff: 'Private items enter selection only when you turn that on under Settings → Moves. Off, nothing here is computed.',
    privateLine: '{name}: mornings after read {with}, against {without} after evenings that started the same ({n} and {m}). An alternative: {alternative}.',
    brings: 'What brings you back',
    bringsLine: '{move} · {n}',
    bringsNone: 'No return after three days away yet.',
    bringsNote: 'The moves done in the day before a Resume that followed three or more days away. A count, not a claim.',
    tagsTitle: 'What the tags have learned',
    tagLine: '{name}: research {research}, your record {record} ({n})',
    tagNone: 'nothing yet',
  },
  history: {
    title: 'History',
    count: '{n} offers',
    empty: 'No moves offered yet. Complete a check-in and one follows.',
    offer: 'Offer {id}',
    card: 'Card {id} · {window}',
    noCard: 'No card',
    outcome: 'Outcome {id}',
    noOutcome: 'No outcome yet',
    pending: 'Pending',
    unanswered: 'Not answered',
    skipped: 'Skipped',
    coinFlip: 'coin flip',
    pickup: 'before pickup',
    study: 'study night',
    step: 'your aim',
    unblock: 'unblocking your aim',
    deleteAnswer: 'Delete the answer',
    deleteConfirm: 'Tap again: it asks you again next time',
  },
  aims: {
    yourAims: 'Your aims',
    kinds: { certification: 'Study', person: 'A person', path: 'A path', practice: 'A practice' },
    kindNotes: {
      certification: 'Named by you: a certification, a language, an instrument. Its step is the next rung of that subject’s ladder, one sitting.',
      person: 'Its step is one move from the people family, yours to keep or change.',
      path: 'A staged curriculum of reps, one a day, picked for who is around.',
      practice: 'Its step is one practice from faith, movement or steadying, yours to keep or change.',
    },
    commitments: 'Your commitments',
    none: 'No commitments yet. Add one; there is nothing to type.',
    add: 'Add a commitment',
    addNote: 'Study is named by you and chooses its six proofs once; a practice picks a step from the catalogue; the Social path picks one rep a day for who is around.',
    studyName: 'What are you learning?',
    studyNamePlaceholder: 'A certification, a language, an instrument',
    studyNote: 'One name, typed once, kept on the phone. Its skills go on the proof ladder under that name; the step is always the next rung.',
    studyLadder: 'Its six proofs',
    studyAdd: 'Add',
    startedShort: 'Started',
    blockedShort: 'Last time: {why} · {unblock}',
    skillsOn: '{n} skills on its ladder',
    skillOne: 'One skill on its ladder',
    noSkillsYet: 'No skills under it yet: add the first here, or on the proof ladder.',
    addSkillHere: 'Add a skill',
    skillPlaceholder: 'One skill',
    nameIt: 'Name it',
    namePlaceholder: 'What this study is',
    when: 'When',
    cues: { afterPickup: 'After pickup', afterBedtime: 'After her bedtime', nextCheckIn: 'Next check-in' },
    planned: 'Planned · {cue}, {time}',
    changePlan: 'Change',
    cueLine: '{cue} · started {started} of {n} planned',
    cueNote: 'One tap says when. Counts only: plans made under each cue, and how many were started.',
    moved: '{skill} advanced to {rung}.',
    stayed: '{skill} already stood at {rung}.',
    lastMoved: { today: 'moved today', yesterday: 'moved yesterday', days: 'last moved {n} days ago', never: 'not moved yet' },
    lastDone: { today: 'done today', yesterday: 'done yesterday', days: 'last done {n} days ago', never: 'not done yet' },
    proofs: '{kind} proofs',
    changeProofs: 'Change the proofs',
    proofsNote: 'The marks stay: each rung keeps its number and takes the new words.',
    allAdded: 'All three kinds are in place.',
    pickStep: 'Pick the step',
    pickNote: 'One line sized to one sitting. Change it any time from Aims.',
    sized: '{n} min · sized to one sitting',
    resume: 'Resume',
    started: 'Started · asked at your next check-in',
    remove: 'Remove',
    changeStep: 'Change the step',
    protectedNote: "Held above the move on Now. Tonight's reading never pushes it aside; you always decide.",
    blocked: 'Last time: {why}. The offer removes the obstacle, never shrinks the aim:',
    blockedWhy: { noTime: 'no time', didntWant: "didn't want to", tired: 'tired', tooMuch: 'too much on', unsaid: 'not now, no reason given' },
    unblockStart: 'Do it',
    her: 'Her',
    herNote: 'Her skills from the checklists and your moments together, counts only.',
    ladder: 'The proof ladder',
    ladderNote: 'Six proofs per skill, counts only. A skill moves only by your tap: Done on its step, which says so where you tapped, or the taps here.',
    follow: 'Follow-through',
    followNote: 'Counts only. Started and finished, across moves, steps and minimum wins.',
    followLine: '{started} started, {finished} finished',
    followMoves: 'Moves',
    followSteps: 'Steps',
    followWins: 'Minimum wins',
    becoming: 'Becoming',
    becomingNote: 'Your direction, shown back unchanged, and dated counts from what was marked done.',
    noDirection: 'No direction line yet. Settings → Your direction.',
    counts: { study: 'Study sessions resumed', conversations: 'Conversations started', timeWithHer: 'Time with your daughter', faith: 'Faith practices you chose' },
    countLine: '{n} · last {date}',
    countNone: 'None marked done yet',
    dataNote: 'Commitments, skills and marks are part of your record. Removing one keeps its record; nothing is graded.',
  },
  path: {
    names: { social: 'The Social path', partner: 'The Partner path' },
    social: 'The Social path',
    socialNote: 'Six stages, from being present where people are to hosting and deepening. One rep a day, picked for who is around.',
    stage: 'Stage {n} of {of} · {name}',
    where: 'Where: {where}',
    movesStage: 'Moves the stage',
    warmUp: 'A warm-up: it does not move the stage.',
    reentry: 'After a quiet stretch: reps from the stage below, while your stage stands.',
    none: { morning: 'No people rep fits this morning.', afternoon: 'No people rep fits this afternoon.', evening: 'No people rep fits tonight.' },
    yours: 'Your pick',
    change: 'Change',
    changeTitle: 'Change the rep',
    changeNote: 'Every rep of this stage. One you pick is today’s, whatever today’s shape says.',
    notAround: 'Nobody around by today’s shape',
    counts: 'What counts',
    notProgress: 'Not progress here',
    byRep: 'Your reps',
    repLine: '{rep} · done {done} · partly {partly} · no {no}',
    noReps: 'No rep marked yet.',
    lastRep: 'Last rep: {rep}, {when}',
    pause: 'Pause the path',
    unpause: 'Take the path up again',
    paused: 'Paused: no row on Now and no step. The record is kept.',
    convert: 'Convert to the Social path',
    convertNote: 'The same commitment, with its whole record: its plans, its steps and their answers.',
    shape: {
      unknown: 'Today’s shape is not written yet',
      office: 'the office',
      church: 'church',
      daycare: 'drop-off or pickup',
      around: 'People around by today’s shape: {why}',
      nobody: 'Nobody around by today’s shape',
      outReason: 'Nobody is around in this block by today’s shape, so in-person reps wait.',
    },
  },
  her: {
    title: 'Her',
    source: 'Skills from the {who} “Learn the Signs. Act Early.” milestone checklists for 4 years and 5 years, the {year} lists. Counts only: never a percentage, a bar, a grade or a comparison with other children.',
    moments: 'Moments with her',
    momentsNone: 'None counted yet.',
    momentsOne: '1 moment · {first}',
    momentsLine: '{n} moments · first {first} · last {last}',
    practiceDone: 'Practice moves done: {n} · last {last}',
    practiceNone: 'Practice moves done: none yet.',
    countMoment: 'Count a moment',
    skills: 'Her skills',
    noSkills: 'No skills on the list yet. Add one from the checklists; nothing to type.',
    addSkill: 'Add a skill from the checklists',
    addNote: 'Four areas, the lists for 4 and 5 years. Tap one to watch it.',
    rungNote: 'A rung moves only by your tap. A count never moves it.',
    note: 'Counts only: no percentage, no bar, no grade, no comparison with other children.',
    rungs: ['Not introduced', 'Practicing with Daddy', 'Needs support', 'Doing sometimes', 'Doing often'],
    noCount: 'No count yet',
    countsLine: 'Did it {did} · on her own {own} · a little help {some} · a lot of help {lots}',
    lastOn: 'last {day}',
    countOne: 'Count one',
    rung: 'Rung',
    remove: 'Remove',
    helpQuestion: 'How much help did she need?',
    help: { own: 'On her own', some: 'A little help', lots: 'A lot of help' },
    pickTitle: 'The checklists',
    by: 'By {age}',
    onList: 'On the list',
    addTap: 'Add',
  },
  ladder: {
    title: 'The proof ladder',
    intro: 'Each skill climbs six proofs. Counts only: no percentages, no bars, no readiness score.',
    skills: 'Skills',
    noSkills: 'No skills yet. Add the skills your study proves, one line each, typed here, never shipped; a subject when there is more than one.',
    addSkill: 'Add a skill',
    skillPlaceholder: 'One skill',
    subjectPlaceholder: 'Subject, if more than one',
    subjectNote: 'A second certification or a language sits beside the first, its skills under its own name. The step follows the skill you moved most recently, whichever subject it belongs to: returning beats starting.',
    add: 'Add',
    up: 'Next rung',
    back: 'Back one',
    remove: 'Remove',
    rungs: ['Not started', 'Watched or read', 'Practiced', 'Built once', 'Broke and fixed', 'Explained from memory', 'Resume bullet'],
    steps: ['watch or read it', 'practise it', 'build it once', 'break it and fix it', 'explain it from memory', 'write the resume bullet'],
    what: [
      'One video or chapter on it, start to finish, notes closed.',
      'Do it once with the material open. Getting it wrong is the point.',
      'Make one small working thing with it, from nothing, no template.',
      'Break the thing you built on purpose, then fix it without looking anything up.',
      'Explain it out loud from memory, as if teaching, until it holds together.',
      'Write the one resume line this proves, with what you built and what it did.',
    ],
    countLine: '{n} at {rung}',
    kinds: { technical: 'Knowledge', language: 'Language', craft: 'Performance' },
    kindLabel: 'Which six proofs',
    kindNote: 'Chosen once; changed on its card, the marks stay. Knowledge, for a certification or anything you build with and explain: watched or read, practised, built once, broke and fixed, explained from memory, resume bullet. Language: heard or read, said, used with notes, used from memory, caught live, used with someone. Performance, for an instrument or a craft: watched or listened, tried slowly, done with the material, done from memory, done clean three times, done for someone.',
    noSubjects: 'Add a study commitment under Aims first; its skills go here under its name.',
    subjectPick: 'Under',
    craft: {
      rungs: ['Not started', 'Watched or listened', 'Tried slowly', 'Done with the material', 'Done from memory', 'Done clean three times', 'Done for someone'],
      steps: ['watch or listen to it', 'try it slowly', 'do it with the material', 'do it from memory', 'do it clean three times', 'do it for someone'],
      what: [
        'Watch or listen to it done well, once through, hands off.',
        'Try it slowly with the material in front of you. Getting it wrong is the point.',
        'Do it once through at speed with the material open.',
        'Do it once through with nothing open, from memory.',
        'Three times in a row from memory without a stumble. One stumble starts the count again.',
        'Do it for someone, in the room or on a call; or record it and let someone see or hear it.',
      ],
    },
    language: {
      rungs: ['Not started', 'Heard or read', 'Said', 'Used with notes', 'Used from memory', 'Caught live', 'Used with someone'],
      steps: ['hear or read it', 'say it', 'use it with notes', 'use it from memory', 'catch it live', 'use it with someone'],
      what: [
        'Hear it or read it from a native speaker, once through, notes closed.',
        'Say it out loud after the model, a few times, material open. Getting it wrong is the point.',
        'Put it into three sentences of your own, said or written, material open.',
        'Three sentences of your own with nothing open, from memory.',
        'Catch it at native speed, in a video, a podcast or an article, and understand it without stopping or looking it up.',
        'Use it in a real exchange with a person, spoken or written: a tutor, a partner, a message, a call.',
      ],
    },
    emptyStep: 'With no skills on the ladder, the step is the catalogue’s own: write the exact next study step.',
  },
  movesTab: {
    historyNote: 'Every offer, its card, and what happened, as three separate records.',
    evidenceNote: 'Every active card with its tier, counts and interval; the tags; the weight card; the associations.',
    tiersNote: 'Tiers are computed, never typed. Confirmatory claims rest on the coin-flip slice; a move is never retired.',
  },
  data: {
    title: 'Data',
    export: 'Export',
    exportNote: 'Everything you recorded, as JSON and CSV, handed to the share sheet. The app sends nothing anywhere.',
    includePrivate: 'Include private items by name',
    exportButton: 'Export JSON and CSV',
    exporting: 'Preparing…',
    lastExport: 'Last export {when}.',
    neverExported: 'Not exported yet.',
    exportFailed: 'The share sheet did not open. Try again from the installed app.',
    importTitle: 'Import a hypothesis',
    importNote: 'An outside hypothesis enters only as a card to test, never as something to believe. Paste one line of JSON: move, alternative, target, context.',
    importPlaceholder: '{"move": "walk-ten", "alternative": "nap-ten", "target": "energy", "context": "afternoon"}',
    importButton: 'Add the card',
    importDone: 'Card written. It shows under Moves → Evidence and nowhere else.',
    importErrors: {
      notJson: 'That is not JSON.',
      fields: 'Four fields are needed: move, alternative, target, context.',
      move: 'The move is not in the catalogue.',
      alternative: 'The alternative is not in the catalogue (or "nothing").',
      target: 'The target must be one of the six ingredients.',
      context: 'The context must be morning, afternoon or evening.',
      same: 'The move and the alternative are the same.',
    },
    deleteTitle: 'Delete everything',
    deleteNote: 'Every check-in, win, private item and setting on this phone, and this app’s rows in your cloud copy when a token is set. Nothing comes back.',
    deleteCloudFirst: 'The cloud copy is deleted first. If it cannot be reached, nothing is deleted.',
    deleteCloudFailed: 'The cloud copy could not be reached, so nothing was deleted. Try again online, or remove the token under Cloud copy first.',
    deleteStart: 'Delete everything',
    deleteWord: 'delete',
    deletePrompt: 'Type {word} to confirm.',
    deleteConfirm: 'Delete it all',
    deleteCancel: 'Keep it',
  },
  settings: {
    checkins: 'Check-ins',
    depth: 'Depth',
    depthFull: 'Full',
    depthShort: 'Short',
    depthNote: 'Short asks mood, energy and stress in every block.',
    frequency: 'Frequency',
    freqThree: 'Three a day',
    freqTwo: 'Morning and evening',
    freqOne: 'Evening only',
    lowDemand: 'Low-demand mode',
    lowDemandNote: 'For rough weeks: short depth, evening only, one reminder, no move, no coin flips. Off restores what you had.',
    quiet: 'Quiet hours',
    quietFrom: 'From',
    quietTo: 'To',
    quietNote: 'No reminders in quiet hours.',
    reminders: 'Reminders',
    remindersOn: 'Remind me',
    reminderTime: '{block} reminder',
    remindersNote: 'One reminder per block, worded the same every time. None in quiet hours, none for a block already begun.',
    inAppNote: 'With the app open in the background it reminds you itself at these times. To be rung with the app closed, set up the ping.',
    remindersDenied: "Notifications are off for this app in the phone's settings.",
    remindersUnsupported: 'This browser offers no notifications here.',
    pushTitle: 'The ping',
    pushSetup: 'Set up the ping',
    pushCopy: 'Copy address',
    pushCopied: 'Copied',
    pushShow: 'Show address',
    pushHide: 'Hide address',
    pushUnsubscribe: 'Unsubscribe',
    pushSubscribedAt: 'Set up {when}.',
    pushChanged: 'The address changed. Copy it again and paste it into the brain’s secret named PUSH_SUBSCRIPTION.',
    pushUnsupported: 'This browser has no push here. Open the installed app on the phone.',
    pushNote:
      'A content-free ping arrives at 07:30, 13:00 and 19:30 (America/New_York), at the moment of a cue you planned, and once more forty-five minutes on if that step is still not started, sent by the Worker under your own account. The worker on this phone decides whether to show anything. This address carries no content, and Unsubscribe kills it. Paste it once into the brain’s secret named PUSH_SUBSCRIPTION.',
    movesSection: 'Moves',
    offerFaith: 'Offer faith moves',
    offerFaithNote: 'Off hides the whole family with one tap. Nothing is counted either way.',
    privateInSelection: 'Use private items to pick moves',
    privateInSelectionNote: 'Off on a fresh install. On, an evening card says what the record associates with an item, like for like, and names an alternative. Never "don’t".',
    extras: 'Evening extras',
    extraWin: "Tomorrow's minimum win",
    extraCaffeine: 'Caffeine',
    extraDinner: 'Late or heavy dinner',
    extraPrivate: 'Private log',
    extraFaith: 'Felt close to God today?',
    faithNote: 'Off stays off until you turn it on here. Never counted, never a streak.',
    more: 'More',
    dataRow: 'Data',
    dataRowNote: 'Export everything, or delete everything.',
    private: 'Private',
    privateNote: 'Items you name, measured, shown nowhere else unless you choose.',
    readingsRow: 'Readings and chips',
    readingsRowNote: 'Retirement proposals, chips that stopped appearing, anchor swaps.',
    wording: 'Wording',
    wordingNote: 'The 13 readings, their 65 phrases, and 48 alternates for your veto.',
    legend: 'Legend',
    legendNote: 'How facts, calculations and conclusions are told apart.',
    about: 'About',
    app: 'App',
    build: 'Build',
    builtAt: 'Built',
    run: 'Open the run that tested this build',
    runMissing: 'Built outside the pipeline, so there is no run to show.',
    testsOne: '{n} unit test passed before this build.',
    testsMany: '{n} unit tests passed before this build.',
    testsUnknown: 'Test count not recorded for this build.',
    data: 'Data',
    dataNote: 'The phone is the source of truth. A copy syncs to your own database once you paste its token under Cloud copy. The brain, a Worker under your own Cloudflare account, reads a sheet derived from your record, your recent notes and private items included, and asks a model there that does not train on it. No other party receives any of it. Nothing else leaves the phone but the ping address, if you set one up, and whatever you choose to export.',
    cloudRow: 'Cloud copy',
    cloudRowNote: 'Paste the token once; the copy syncs on its own.',
  },
  private: {
    title: 'Private',
    note: 'Named here only. Part of your cloud copy like everything else, by your choice. Never in an export unless you tick them. Never in any document.',
    none: 'Nothing named yet.',
    placeholder: 'Name it',
    add: 'Add',
    remove: 'Remove',
    show: 'Show private items by name outside this screen',
  },
  brain: {
    grades: { A: 'strong evidence', B: 'good evidence', C: 'some evidence', D: 'thin evidence' },
    tapLabel: 'Was this worth hearing',
    useful: 'Useful',
    knew: 'Knew it',
    not: 'Not useful',
    noted: 'Noted. It shapes what is said next.',
    actionPlan: 'Plan it: {cue}, {time}',
    actionDepth: 'Switch to short depth',
    actionTest: 'Set the test: {move}',
    acted: { plan: 'Planned for today.', depth: 'Short depth is on; Settings changes it back.', test: 'The test is set; its card is under Evidence.' },
    why: 'Why',
    whyLine: 'Why this line',
    whyAlso: 'Also from your record',
    whyWriter: 'Written by',
    fromPhone: 'Chosen on this phone from your record, by the situation engine.',
    writerTag: 'Brain',
    whyFacts: 'From your record',
    whyNoFacts: 'The facts under this line have not reached this phone yet.',
    whyCards: 'From the library',
    whyCard: '({grade}; {effect}. {source})',
    review: {
      title: 'The week, reviewed',
      held: 'What held',
      didNot: 'What did not',
      change: 'One change',
      heldItem: '{name}: {n} started, {done} done.',
      missedItem: '{name}: none in the last seven days.',
      newToday: '{name}: added today, no step started yet.',
      newYesterday: '{name}: added yesterday, no step started yet.',
      newItem: '{name}: added {d} days ago, no step started yet.',
      noCommitments: 'No commitment is on the record yet.',
      nothingYet: 'Nothing to set against the week yet.',
      missedCadence: 'Check-ins: {now} this week against {before} the week before.',
      noneHeld: 'No commitment had a step started in the last seven days.',
      noneMissed: 'Every commitment had a step started.',
      noChange: 'Nothing the record supports changing; keep the cues that hold.',
      fromWorker: 'Written by the brain under your account, {model}, from the week’s facts and the library.',
      fromPhone: 'From the record alone; the brain writes a fuller one on Sundays.',
    },
    fromWorker: 'Written by the brain under your account, {model}, from the facts and the library.',
    lines: {
      stretch: '{under} of the last {of} blocks read under their usual low. A stretch is starting. One easy move a day, kept, is what turns these; the mood follows the doing.',
      'necessities-missed': '{n} necessities missed in three days. That is the earliest sign of a stretch; the smallest one first, before any move.',
      'loneliness-high': 'Loneliness read “{word}” at the last check-in. One small contact today, a message or a question to someone: small ones move it.',
      'cue-switch': '{cue} kept {started} of {n} plans. Plans stall on the cue, not on the will: try {other}.',
      'first-skill': '{name} has no skill on its ladder yet. Add the first; nothing can move until it does.',
      'study-no-time': 'No time ended {n} of the last study nights. That is a cue problem, not a will problem: pin the step to after her bedtime.',
      'caffeine-sleep-shorter': 'After days with {high} of caffeine reported, {what} the next night than after days with {low} ({m} and {n} days, like for like on the sleep the day began with). An association in your record, not a verdict.',
      'ladder-flat': '{name}: {k} skills on the first rungs and none higher. Take one to from memory before starting another; retrieval is where it sticks.',
      'step-stalled': '{name} has not moved in {d} days. The smaller version tonight counts, and a gap does not undo what was built.',
      'nap-read': 'Mornings after a nap read {diff} against the mornings without, {n} naps. Short naps help the afternoon; long ones cost the night.',
      'workout-evenings': 'Evenings of workout days read {diff} above the others, {n} days. Exercise is the best-supported lever there is for mood, and the record agrees.',
      'workout-flat': 'Evenings of workout days read {diff} against the others, {n} days. The evidence for exercise and mood is strong; the record here does not show it yet, and timing may be why.',
      'social-recovery': 'Mornings after a big social event read {diff} under the others, {n} times. A quieter next day is the cost of it, not a flaw in it.',
      'study-tired': 'Tired ended {n} of the last study nights. The ten-minute sitting after her bedtime is the honest size; short sittings on more days beat one long one.',
      'cue-holds': '{cue} has held {started} of {n} times. Keep that cue; it is doing the work.',
      'say-when': '{name}: the step is {step}. Say when, one tap. A plan tied to a moment is kept far more often than a wish is.',
      'afternoon-walk': 'The afternoon usually reads {point} here. A ten-minute walk at midday lifts mood at once, whatever you expect of it.',
      'partly-honest': 'Partly, {n} times this week. Partly is a start; the smaller version is the honest size, and it is the one that gets kept.',
      'card-long-unclear': '{move} against {alt}: {n} observations and no clear difference. Change the alternative or retire the card; the tries already made are no reason to keep it.',
      'card-promising': '{move} against {alt}: {tier}, {n} observations. Worth one more week before believing it.',
      'caffeine-late': '{when}, {band} was reported at the {block} check-in, {time}. A meta-analysis of trials put the point where about {mg} mg stops shortening sleep at {hours} hours before bed; counted from {time}, that runs past midnight.',
      'church-morning': 'Mornings after church read {with} against {without} on other mornings, {n} times. The recovery gap is a fact of the day, not of you.',
      'steady-moving': 'Steady, {inside} of {of} blocks inside the usual, and {name} moved this week. Progress that is recorded carries part of the effect by itself.',
      'fresh-start': 'A {weekday}. Fresh starts are measurably easier to begin on, and {name}, {d} days still, is the one to restart.',
      'nothing-holds': 'Nothing extra was kept {done} of the {offered} times it was offered. Rest is a move; the mornings after say what it does.',
      'direction-counts': 'Your direction: “{direction}”. So far {study} study sessions, {conversations} conversations started, {faith} practices, {her} times with her. Counts, not a verdict.',
      'forecast-wide': 'The model’s range for the {block} runs {lo} to {hi}: a guess. Your own reading at the check-in is the better guide today.',
      'caffeine-sleep-even': 'Next nights show no difference yet between days with {low} and days with {high} of caffeine reported ({n} and {m} days). Self-reported sleep is known to miss caffeine’s effect.',
      'commitment-fading': '{name}: {before} sittings in the two weeks before, none in the last two. This is where a commitment is usually let go, and it is the cue that goes first, not the will. Pin the smallest sitting to a moment today.',
      'commitment-thinning': '{name}: none in the last seven days, after {before} the week before. One short sitting keeps the thread; pin it to a moment today.',
      'cadence-dropping': 'Check-ins went from about {usual} a week to {now}. Before the record goes quiet, make it lighter: short depth asks three readings and keeps everything else working.',
      'loop-closed': 'Yesterday’s line was about {name}; since then the record shows {what}. That is the loop closing.',
      'loop-planned': 'Yesterday’s line was about {name}: a plan was made, and its moment passed without a start. One plan says little about you and something about the moment; pin the step, or a smaller one, to a moment that has held before.',
      'loop-open': 'Yesterday’s line was about {name}, and the record shows nothing on it since. If the suggestion was wrong, Not useful says so; if the step is too big, pin its smaller version to a moment today.',
      'short-night-today': 'Sleep read “{word}” this morning. Short sleep lowers mood more than it lowers thinking, so read today’s numbers in that light; a nap under half an hour before mid-afternoon is the supported repair.',
      'short-sleep-afternoons': 'Afternoons after short nights read {diff} against the others, {n} mornings. Regular hours count for more than long ones.',
      'propose-test': 'The library holds {grade} for {move}, and your record has never tested it. One tap sets the test against nothing extra; its card will say what your record finds.',
    },
  },
  cloud: {
    title: 'Cloud copy',
    intro: 'The phone is the source of truth. A copy of everything you record syncs to your own database. The brain, a Worker under your own Cloudflare account, reads a sheet derived from that record, your recent notes and private items included, and asks a model there that does not train on it. No other party receives any of it.',
    url: 'Database',
    urlNote: 'A constant, not a secret. Shown so you can match it against your Turso dashboard.',
    token: 'Token',
    tokenPlaceholder: 'Paste the token once',
    tokenSet: 'Token stored on this phone.',
    tokenNote: 'Created in your Turso dashboard, pasted once, stored in this app’s storage on the phone. It never appears in source, tests, the pipeline or logs.',
    keep: 'Keep it',
    remove: 'Remove the token',
    status: 'Status',
    off: 'Sync is off until a token exists.',
    lastSync: 'Last sync {when}',
    never: 'Not synced yet',
    pending: '{n} pending',
    pendingNone: 'nothing pending',
    syncing: 'Syncing…',
    offline: 'Offline; changes wait here.',
    error: 'Last attempt did not go through: {error}. It retries on its own.',
    syncNow: 'Sync now',
    device: 'This phone',
    limit: 'One phone per app for now: local ids are numbered per device. A second phone needs string ids first.',
    restoreNote: 'On a fresh install, paste the token and the first sync restores everything.',
    outside: 'It also reads the finished workouts your other app writes to the same database, so a workout day is known here: never a move, never a count, a fact the record sets against the others.',
    brain: 'The brain is a Worker under your own account that reads the day’s facts from this database, a library of graded evidence shipped with the app, and writes one line back; the phone shows it on the brief. The facts carry the last few notes you typed at a check-in, so the line can read them; on Sundays it also writes the week’s review. The phone’s own line stands whenever the Worker has not written.',
    brainStatus: 'Last line from the brain {when}, {model}.',
    brainNone: 'Nothing from the brain yet.',
    tokenMissing: 'The token went missing from this phone on {when}. Paste it again; the first sync then pulls everything back.',
    lastSeen: 'last seen {when}',
    notKept: 'The token did not stay in the app’s database. Try again.',
    tokenLog: 'Token log',
    logSaved: 'Pasted in Settings.',
    logSavedNoMirror: 'Pasted in Settings. The phone’s second copy could not be written.',
    logSecondCopy: 'A second copy of the token was written to the phone’s local storage, and the whole history was checked against the cloud copy.',
    logLocalRestored: 'The phone’s second copy of the token was missing and was written again from the app’s database.',
    logDatabaseRestored: 'The app’s database had lost the token; it was written again from the phone’s second copy, and the whole history was pulled back.',
    logDisagreed: 'The two copies of the token disagreed; the more recently saved one was kept.',
    logMissing: 'The token is missing from both the app’s database and the phone’s second copy. Paste it again and the first sync pulls everything back.',
    logRemoved: 'Removed in Settings.',
  },
  legend: {
    title: 'Legend',
    intro: 'Three kinds of thing appear on screen, and they always look different.',
    facts: 'Facts',
    factsNote: 'What you tapped and when. Plain text.',
    calcs: 'Calculations',
    calcsNote: 'Numbers the app derives from facts, always with their recipe. Set off by a thin rule on the left; every chart carries its caption.',
    conclusions: 'Conclusions',
    conclusionsNote: 'What the app claims to have learned. Set off by a double rule on the left, and always with its evidence tier: Little evidence, Unclear, Promising, Holds up, Unhelpful here.',
    recipe: 'The reading out of 100',
    recipeNote:
      'Six readings have a clear better direction: mood, energy and focus up; stress, overwhelm and irritation down. Each phrase maps to 0, 25, 50, 75 or 100, reversed where lower is better. The reading is the equal-weight mean of the ones asked. At full depth every block asks all six, and a block missing any of them reads Incomplete, never a number. At Short depth a block asks three (mood, energy and stress), and its reading is the mean of those three, printed as 3 of 6; it compares only loosely with a full one. Weights stay equal until a weight card holds up on your record.',
    stances: 'The five bands',
    stancesNote: '0 to 19 Empty · 20 to 39 Worn down · 40 to 59 Getting by · 60 to 79 Solid · 80 to 100 Firing. Descriptions of a state, never a verdict. From 80 the band’s name turns the accent; the number stays white.',
    context: 'Context',
    contextNote: 'Hunger, sleep, confidence, loneliness and social energy sit beside the reading. They never enter it.',
    silence: 'Silence',
    silenceNote: 'An unanswered question shows Not logged yet. It changes no number, fills no gap on a chart, and prompts no catch-up.',
  },
  wording: {
    intro: 'Five phrases per reading, least to most. You pick a phrase, never a number.',
    sets: 'Morning asks all 13. Afternoon asks seven: mood, irritation, energy, hunger, stress, focus, overwhelm. Evening asks those and loneliness. Every block feeds all six ingredients of the reading.',
    alternatesNote: 'Under each phrase but the middle, one pre-written alternate for your veto. A swap happens only after forty-five days in which a phrase was never tapped across thirty answers, once per reading, never the middle, logged and dated.',
    alternate: 'or: {phrase}',
    swapped: 'swapped in on {date}; was “{from}”',
  },
  reminders: {
    body: 'Time for your {block} check-in.',
    quiet: 'Nothing due right now.',
    test: 'The brain can reach this phone.',
    stillOpen: 'Still open',
  },
} as const
